### ISSUE TITLE
extend the formula interface to gene set enrichment analysis

### ISSUE THREAD

**Issue by dalloliogm** [YuLab-SMU/clusterProfiler#15]
Hi Guangchuang,
I was wondering if the formula interface of compareCluster could be modified to include also gene set enrichment analysis like gseGO.

If I understand correctly, compareCluster can be used to apply gseGO and others to list of lists of genes:

```
> mylist = list('a'=geneList[0:200], 'b'=geneList[200:400])
> compareCluster(mylist, fun='gseGO')
```

I wonder how this could be extended to the formula interface. The major difficulty is to define the column containing expression values.

```
> mydf = data.frame('entrez'=names(geneList)[0:400], 'expression'=geneList[0:400], group=c(rep('a', 200), rep('b', 200)))
```

**option 1: using a new parameter**
`> compareCluster(data=mydf, entrez~group, scores=expression, fun='gseGO')`

**option 2: including it in the formula**
`> compareCluster(data=mydf, expression | entrez~group, scores=expression, fun='gseGO')`
Which option is nicer?

**Comment by GuangchuangYu** [comment]
In option 2, I think you mean:
compareCluster(data=mydf, expression | entrez~group, ~~scores=expression,~~ fun='gseGO')

I prefer this one, since it's more compact.

**Comment by yangzk1201** [comment]
> dat
               ID                                                Description GeneRatio BgRatio      pvalue   p.adjust
map05323 map05323                                                       <NA>      4/12 73/1728 0.001122688 0.01767108
map03020 map03020                                             RNA polymerase      6/30 73/1728 0.001224728 0.01767108
map00240 map00240                                      Pyrimidine metabolism      9/67 73/1728 0.001539568 0.01943704
map05169 map05169                                                       <NA>      8/58 73/1728 0.002402823 0.02381438
map00190 map00190                                  Oxidative phosphorylation      8/59 73/1728 0.002686371 0.02381438
map05120 map05120 Epithelial cell signaling in Helicobacter pylori infection      4/15 73/1728 0.002810322 0.02381438
map04150 map04150                                     mTOR signaling pathway      6/35 73/1728 0.002829431 0.02381438
             qvalue                                          geneID Count
map05323 0.01767108                             VMA2/VMA1/VMA8/VMA7     4
map03020 0.01767108                RPB9/RPB4/RPO26/RPB2/RPC10/RPC11     6
map00240 0.01943704 RPB9/RPB4/RPO26/RPB2/PNP1/TRR2/URA3/RPC10/RPC11     9
map05169 0.02381438      RPB9/RPB4/RPO26/RPB2/SUA7/RPT4/RPC10/RPC11     8
map00190 0.02381438       VMA2/ATP1/VMA1/COX4/VMA8/COX5A/VMA7/ATP18     8
map05120 0.02381438                             VMA2/VMA1/VMA8/VMA7     4
map04150 0.02381438                 SEC13/VMA2/VMA1/VMA8/CDC33/VMA7     6
> dotplot(dat,x=~Cluster, colorBy="p.adjust", showCategory=5, by="geneRatio", includeAll=TRUE, font.size=12, title="")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dotplot’ for signature ‘"data.frame"’

Hi, prof.GuangchuangYu, I got a wrong message, could you help me check this problem?

**Comment by GuangchuangYu** [comment]
`dotplot` is only work for `enrichResult` and `compareClusterResult`, but not `data.frame`.

pls read the vignettes, <https://guangchuangyu.github.io/clusterProfiler/documentation/#vignettes>.

**Comment by alnf** [comment]
I've just started using clusterProfiler, and I also came up with the similar question as @dalloliogm. What is the status of this enhancement now?

**Comment by briverog** [comment]
> In option 2, I think you mean:
> compareCluster(data=mydf, expression | entrez~group, ~scores=expression,~ fun='gseGO')
> 
> I prefer this one, since it's more compact.

Hi Guangchuang, 

I have successfully used compareCluster with enrichGO function. However, it does not work with fun =  gseGO, and I can not reproduce the example above. 

head(mydf)
              entrez expression group
43849  43849   3.975204     a
2892       2892   3.730853     a
90070  9 0070   3.438285     a
3547       3547   3.264492     a
10879    10879   2.699081     a
6690       6690   2.582944     a

compareCluster(data=mydf, expression | entrez~group, fun='gseGO',
               OrgDb= org.Hs.eg.db, 
               ont= "BP", 
               keyType = "ENTREZID",
               exponent = 1,
               minGSSize = 10,
               maxGSSize = 500,
               eps = 1e-10,
               pvalueCutoff = 0.05,
               pAdjustMethod = "BH",
               verbose = TRUE,
               seed = FALSE,
               by = "fgsea")

The compareCluster documentation for fun argument does not list gseGO within its options (One of "groupGO", "enrichGO", "enrichKEGG", "enrichDO" or "enrichPathway"), but I see online people manage to do it with the formula interface. Is it still possible to do it or has been disable for newer clusterProfiler versions?

Thanks,
Belén
