### ISSUE TITLE
Plot empty groups in dotplot

### ISSUE THREAD

**Issue by guillermomarco** [YuLab-SMU/clusterProfiler#157]
Hello, I'm following the example of #32 and docs to plot `compareCluster` enrichment analysis. However I'm missing some groups that have no GO terms in this case. Is it possible to make dotplot show empty groups? As you can check in the picture below, I'm missing **BCL10.down** group and I would like to show it on plot even if it has no enrichment results.

Regarding the formula, GROUP represents (CONTROL, BCL10, L8P) and EXPRESSION (UP or DOWN)

`ck_go_exp<-compareCluster(ENTREZID~GROUP+EXPRESSION, data=df, fun="enrichGO", OrgDb="org.Hs.eg.db", pvalueCutoff=0.1)`
`dotplot(ck_go_exp, showCategory = 50)`

![go_expression](https://user-images.githubusercontent.com/2011448/44388197-ca3b6d80-a527-11e8-863c-4bb6f4108cbf.png)

**Comment by YichaoCaiDBS** [comment]
Hi all!

I also came across this issue in my pipeline. 

One way to hack around it is to set the threshold to 1 in `compareCluster()` call. This would return all enrichment entries. After that, you can apply your own threshold and use ggplot2 to show all gene set even there is no significant enrichment.

This is how I did this:
```
library(dplyr)
library(ggplot2)
library(clusterProfiler)
library(org.Hs.eg.db)


## This is the compareCluster function call.
egoObj <- compareCluster(geneID ~ group+othergroup, data=rawDF, fun="enrichGO",
                                OrgDb         = org.Hs.eg.db, 
                                keyType       = 'ENSEMBL',
                                ont           = "BP",
                                pAdjustMethod = "BH",
                                pvalueCutoff  = 1,     ## Set p value cutoff to 1 in order to show all results
                                readable      = TRUE)
## Mutate the GeneRatio into double. 
df <- egoObj@compareClusterResult %>% 
            separate(GeneRatio,c("count","total"),sep="/") %>% 
            mutate(GeneRatio = as.double(count)/as.double(total))

## Function to filter first N GO term under specified p.adjust cutoff.
filterCategory <- function(df, N, cutoff){
    df_topn <- NULL
    for(i in levels(df$Cluster)){
       df_slice <- df %>% filter(Cluster == i) %>% 
                             arrange(p.adjust) %>% 
                             filter(p.adjust<cutoff) %>% 
                             head(N)
      df_topn <- bind_rows(df_topn, df_slice)
    }
    return(df_topn)
}
df_top10 <- filterCategory(df,10,0.05)      # Filter the results to show only top 10 GO terms less than p.adjust 0.05 in all cluster.

## Order the GO term in a style similar to dotplot.
orderVec <- NULL
for(i in 1:length(df_top10$Description)){
   if(df_top10$Description[i] %in% orderVec){
      next
    } else {
      orderVec <- c(orderVec,df_top10$Description[i])
    }
}
df_top10 <- df_top10 %>% transform(Description = factor(Description, levels = rev(orderVec)))

## Generate cluster labels like dotplot.
labelDF <- egoObj@compareClusterResult %>% 
               separate(GeneRatio,c("count","total"),sep="/") %>% 
               mutate(GeneRatio = as.double(count)/as.double(total)) %>% 
               dplyr::select(Cluster, total) %>% 
               distinct() %>% 
               mutate(labels = sprintf("%s\n(%s)",Cluster,total))
  
p <- ggplot(df_top10, aes(x=Cluster, y=Description)) +
    geom_point(aes(size = GeneRatio, color = p.adjust)) +
    scale_x_discrete(drop=FALSE, labels=labelDF$labels) +   # drop=FALSE to show all category 
    scale_colour_gradient(limits=c(0, max(df_top10$p.adjust)), low="red",high="blue") +
    theme_bw() +
    theme(axis.title = element_blank())
```

Hope that might help!

It would be great to have `drop = FALSE` option in `dotplot()` to toggle the visualization of emtpy enrichment in clusters.

Cheers,
Yichao

**Comment by dwill023** [comment]
Hi, Anyone know how I can compareCluster between two different DESeq sample groups like in the top comment. I am able to generate the Entrez~group but don't know how I can add another data frame. 

For example I tried: 
# reading in data from deseq2
df1 <- read.csv("s690 sig DEGs.csv")
df2 <- read.csv("t690 sig DEGs.csv")
# we want the log2 fold change 
original_gene_list1 <- df1$log2FoldChange
original_gene_list2 <- df2$log2FoldChange
# name the vector
names(original_gene_list1) <- df1$Gene
names(original_gene_list2) <- df2$Gene
# omit any NA values 
gene_list1<-na.omit(original_gene_list1)
gene_list2<-na.omit(original_gene_list2)
# sort the list in decreasing order (required for clusterProfiler)
gene_list1 = sort(gene_list1, decreasing = TRUE)
gene_list2 = sort(gene_list2, decreasing = TRUE)
# filter on min log2fold change (log2FoldChange > 2)
genes1 <- names(gene_list1)[abs(gene_list1) > 2]
genes2 <- names(gene_list2)[abs(gene_list2) > 1]

mydf <- data.frame(Entrez=names(gene_list2), FC=gene_list2)
mydf <- mydf[abs(mydf$FC) > 1,]
mydf$group <- "upregulated"
mydf$group[mydf$FC < 0] <- "downregulated"
mydf$othergroup <- "t690"

mydf2 <- data.frame(Entrez=names(gene_list1), FC=gene_list1)
mydf2 <- mydf2[abs(mydf2$FC) > 2,]
mydf2$group <- "upregulated"
mydf2$group[mydf2$FC < 0] <- "downregulated"

# I tried 
mydf$othergroup[abs(mydf2$FC) > 2] <- "s690"

But got the error:
Error in `$<-.data.frame`(`*tmp*`, othergroup, value = c("s690", "s690",  : 
  replacement has 3713 rows, data has 716

Not sure how else to generate the additional data as the number of rows are different. Any advice is appreciated.

Thanks,
Desiree

**Comment by GuangchuangYu** [comment]
```
 mydf$othergroup[abs(mydf2$FC) > 2] <- "s690"
```

**mydf** and **mydf2** have different number of rows and the above code is absolutely wrong.
