### ISSUE TITLE
simplify doesn't stop since update yesterday (and update of packages in R 3.5.1)

### ISSUE THREAD

**Issue by gwangjinkim** [YuLab-SMU/clusterProfiler#186]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

**Comment by njmdietrich** [comment]
I have the same issue. Specifically, it just happens when I use the "BP" ontology; "MF" and "CC" work. 
The way I'm applying the method:
`    ego  = enrichGO(gene          = genes,
               OrgDb         = org.Mm.eg.db,
               keyType       = "ENSEMBL",
               ont           = "BP",
               pAdjustMethod = "BY",
               pvalueCutoff  = 0.01
              )
    ego  = simplify(ego)`

**Comment by GuangchuangYu** [comment]
if you want to report an issue, make sure you are using the latest version.

**Comment by njmdietrich** [comment]
Thank you for that hint, I am using conda and had some conflicts with other packages. I created a new environment specifically for clusterprofiler and I can report that using r version 3.6.1 and clusterprofiler version 3.14.0, the issue does not occur.
