### ISSUE TITLE
can enrichKEGG provide a way of using downloaded database 

### ISSUE THREAD

**Issue by LEIyuechen** [YuLab-SMU/clusterProfiler#205]
HI, yu:
      Can enrichKEGG provide a way of using downloaded database?  My servers are not always available to network  so it will help so much if this feature could be added. KEGG.db, as written in the vignette,  is too old. So I want to use the local downloaded database. Thanks .

**Comment by mdozmorov** [comment]
Can be done with minimal data reformatting, as described, https://yulab-smu.github.io/clusterProfiler-book/chapter3.html#clusterprofiler-as-an-universal-enrichment-analysis-tool

For the 2019 version of KEGG, see http://amp.pharm.mssm.edu/Enrichr/#stats

**Comment by GuangchuangYu** [comment]
Here is a solution, <https://github.com/YuLab-SMU/createKEGGdb>.
