### ISSUE TITLE
How to adjust the text information of picture made by 'dotplot {enrichplot}'

### ISSUE THREAD

**Issue by PSSUN** [YuLab-SMU/clusterProfiler#213]
Dear Yu,

I am sorry to bother you in your busy schedule.

Here's my question:
I use dotplot to plot the result of enrichGO with command:
`dotplot(ego_mf, showCategory=25,font.size=15)`
but in the MF text list on the left, there is a result that is so long that it affects the layout of the entire graph.
example:

> neutrophil activation
> RNA splicing, via transesterification reactions 
> RNA splicing, via transesterification reactions with bulged adenosine as nucleophile 
> mRNA splicing, via spliceosome 
> nuclear transport

The third line is too long, squeezing the chart on the right. So I want to divide it into two lines. But I did not find the relevant parameters in dotplot. I remember that you mentioned this problem in biobabble. But I did not find it. Could you please give me some advice about it.

Have a nice day!

**Comment by jllavin77** [comment]
Dear Yu,

I'm facing the same problem. I tried to export to this case the solution given for barplots,

`dotplot(egoBP,font.size=12) + scale_x_discrete(labels=function(egoBP) str_wrap(egoBP, width=10))`

but it doesn't work for dotplot.

Have you provided a solution to this issue, because it severely affects the usability of dotplots for publication purposes when labels are too long...

Thanks in advance

**Comment by jllavin77** [comment]
Dear Yu,
Any insight or example on how to do this?

Thanks

**Comment by PSSUN** [comment]
> 
> 
> Dear Yu,
> Any insight or example on how to do this?
> 
> Thanks
---
Hi,
  I am sure I have find out the way to solve this.
  **please check this link:** [link](https://mp.weixin.qq.com/s/YQZSkzYquYg3LEx433W_WA). 
  Whether your native language is Chinese or not, I believe you can read it because the code and images are displayed in the text.
  Have a nice day!

**Comment by jllavin77** [comment]
PSSUN solution only works for barplots

**Comment by GuangchuangYu** [comment]
use `scale_y_` for dotplot.

**Comment by tilofreiwald** [comment]
Thanks, very helpful comments here. For completeness I'll add the code for `dotplot()` here:

```R
plot1 = dotplot(my.enricher.obj) + scale_y_discrete(labels=function(x) str_wrap(x, width=40))
```

If you curate custom gene lists be aware that for text wrapping to be possible you need spaces in your term titles:

```R
library("msigdbr")
custom.gene.lists = msigdbr(species = "Mus musculus", category = "H") %>% dplyr::select(gs_name, entrez_gene)
custom.gene.lists$gs_name = gsub("_", " ", custom.gene.lists$gs_name, fixed = TRUE)
my.enricher.obj = enricher(my.genes.entrez, TERM2GENE=custom.gene.lists)
```
