### ISSUE TITLE
Error in download.KEGG.Path(species) 

### ISSUE THREAD

**Issue by Yichel518** [YuLab-SMU/clusterProfiler#218]
When I run KEGG analysis of zebrafish , ego <- enrichKEGG(
    gene = dnd_buc_list,
    keyType= "kegg",
    organism= 'dre',
    pvalueCutoff= 0.05,
    pAdjustMethod= "BH",
    qvalueCutoff= 0.05)
I got a error:
Error in download.KEGG.Path(species) : 
  'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...
I do not know why?

**Comment by sunliang3361** [comment]
I have the same issues. Can someone help out here?

**Comment by GuangchuangYu** [comment]
KEGG server is down at that moment or you have internet connection issue.

**Comment by rocketeer1998** [comment]
I'm suffering from the same issue. And I'm wondering if there is another way than just waiting?

**Comment by tester-0102** [comment]
i have exactly the same problem, i cant solve it
RStudio 2022.02.3+492 "Prairie Trillium" Release for Windows
R 4.2.0
i have installed clusterprofiler
error message: 
Reading KEGG annotation online:
fail to download KEGG data...
Error in download.KEGG.Path(species) : 
  Failed to download KEGG data. Wrong 'species' or the network is unreachable. The 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html

test code:
results1 <- enrichKEGG(gene         = gene, organism     = 'hsa', pvalueCutoff = 0.05)

any help; is there any compatibility problem with r or rstudio versions;
thanx
