### ISSUE TITLE
Error in as.vector(x, mode) :    cannot coerce type 'environment' to vector of type 'any'

### ISSUE THREAD

**Issue by guijie2015** [YuLab-SMU/clusterProfiler#220]
Dear Professor:
Hello,I meet a problem when I use enrichKEGG.Here is my code.
Gene <- c("1645","302","305","308","93663","84002", "9529","10134", "586","27319")##a part of my gene
KEGG <- clusterProfiler::enrichKEGG(gene = Gene, organism = "hsa", keyType = "kegg",
                   pvalueCutoff = 0.05, pAdjustMethod = "BH", minGSSize = 1,
                   qvalueCutoff = 0.05, use_internal_data = T,universe = org.Hs.eg.db)

It will print that 
"Error in as.vector(x, mode) : 
  cannot coerce type 'environment' to vector of type 'any'"
Thanks for you to read my command.

**Comment by GuangchuangYu** [comment]
`universe = org.Hs.eg.db`

should be
`
universe = keys(org.Hs.eg.db)
`

**Comment by guijie2015** [comment]
Thanks for your help!
