### ISSUE TITLE
enrichKEGG and gseKEGG doesn't work?

### ISSUE THREAD

**Issue by zhoujj2013** [YuLab-SMU/clusterProfiler#224]
Hi Dr. Yu,

enrichKEGG and gseKEGG function do not work properly. 
When I run the functions, it only stays here without any msg and I can not stop the function.

Could you please help me with this problem?

Thanks a lot.

Jiajian ZHOU

Suppl. R code:
```
> data(geneList, package="DOSE")
> kk2 <- gseKEGG(geneList     = geneList,
            organism     = 'hsa',
            nPerm        = 1000,
            minGSSize    = 120,
             pvalueCutoff = 0.05,
               verbose      = FALSE)

^C^C^C
```

**Comment by GuangchuangYu** [comment]
it should run fast. This may due to your internet issue for downloading KEGG annotation online.

**Comment by zhoujj2013** [comment]
Thanks, the network has some issues in our institute.
