### ISSUE TITLE
pathview doesn't work

### ISSUE THREAD

**Issue by sunliang3361** [YuLab-SMU/clusterProfiler#225]
It seems pathview doesn't work right now.  I even try to use the sample data provided by the author in the tutorial.
See my code and error message below:
data(geneList, package="DOSE")
head(geneList)

hsa04110 <- pathview(gene.data  = geneList,
                     pathway.id = "hsa04110",
                     species    = "hsa",
                     limit      = list(gene=max(abs(geneList)), cpd=1))

error message is below:
Info: Downloading xml files for hsa04110, 1/1 pathways..
Warning: Download of hsa04110 xml file failed!
This pathway may not exist!
Info: Downloading png files for hsa04110, 1/1 pathways..
Warning: Download of hsa04110 png file failed!
This pathway may not exist!
Warning: Failed to download KEGG xml/png files, hsa04110 skipped!
Warning message:
In download.file(xml.url, xml.target, quiet = T) :
  cannot open URL 'http://rest.kegg.jp/get/hsa04110/kgml': HTTP status was '404 Not Found'
>

**Comment by GuangchuangYu** [comment]
this is an issue of `pathview` and you should contact the pkg author.
