### ISSUE TITLE
exporting default TERM2GENE table

### ISSUE THREAD

**Issue by weichen2** [YuLab-SMU/clusterProfiler#230]
Recently, we implemented R package “clusterProfiler” for DAVID pathway enrichment. We would like to export the TERM2GENE table (for option “universe” in function “enrichDAVID”). How can we obtain the TERM2GENE table? Big thanks.

**Comment by GuangchuangYu** [comment]
the `enrichDAVID` submit your input and query result from DAVID. It cannot access the underlying database of DAVID and thus not possible to export the annotation table.

**Comment by weichen2** [comment]
Thanks, Dr. Yu. I see.

**Comment by peranti** [comment]
`RDAVIDWebService` is not available currently and hence we cannot use `clusterProfiler::enrichDAVID()`
