### ISSUE TITLE
enrichResult Error

### ISSUE THREAD

**Issue by MatthewPearsonRA** [YuLab-SMU/clusterProfiler#234]
### enrichResult Error
When running enrichGO analysis on certain sets of genes an error in the creation of the enrichResult output causes it to be unusable in future analysis (dotplots, barplots, conversion to data frame, etc.). In my example below the `S4 object of class enrichResult` has dimensions of `[0 x 9]`, while the data frame contained in results has dimensions of `[356 x 9]`. Whereas in analysis of other gene sets the S4 object has dimensions that are not `[0 x X]`, I think this is causing the issue.

Example:
``` 
genelist <- c("TSBP1", "NOTCH4", "EGFR", "LPP", "HLA-DRA")
egc <- bitr(genelist, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
geneids <- egc$ENTREZID

enrichGOPathways <- enrichGO( gene = geneids,
                      OrgDb         = org.Hs.eg.db,
                      ont           = "BP",
                      pAdjustMethod = "BH",
                      pvalueCutoff  = p_threshold,
                      readable      = TRUE
)
```
Screenshot of enrichResult: ![enrichResult](https://user-images.githubusercontent.com/56873128/70801265-579e7300-1da6-11ea-9c4f-76fba1a7d199.png)

**Comment by deij17** [comment]
Why was this taken off? I am having the same problem!!! did you figure it out?

**Comment by huerqiang** [comment]
@deij17 When you analysis the S4 object, some built-in function, such as as.data.frame(), will filter the "@result"  whith the cutoff of your pvaluecutoff.
