### ISSUE TITLE
read.gmt() fails on wikipathways-20191210-gmt-Mus_musculus.gmt

### ISSUE THREAD

**Issue by droeatumn** [YuLab-SMU/clusterProfiler#238]
Following the directions here[1] and using clusterProfiler 3.6.0, I find that read.gmt() fails on this[2] file. When I download it and run via:

```
wp2gene <- read.gmt('/home/roex0050/data/wikipathways-20191210-gmt-Mus_musculus.gmt')
wp2gene <- wp2gene %>% tidyr::separate(ont, c("name","version","wpid","org"), "%")
```

If fails with

```
Error in wp2gene %>% tidyr::separate(ont, c("name", "version", "wpid",  : 
  could not find function "%>%"
```

1. https://yulab-smu.github.io/clusterProfiler-book/chapter3.html#wikipathways-analysis
2. http://data.wikipathways.org/current/gmt/wikipathways-20191210-gmt-Mus_musculus.gmt

**Comment by chansigit** [comment]
you need to load library(magrittr) to use the %>% symbol

**Comment by droeatumn** [comment]
Thank you.

**Comment by AhmedEzatElZowalaty** [comment]
> wp2gene <- wp2gene %>% tidyr::separate(ont, c("name","version","wpid","org"), "%")
Error: object 'ont' not found
Run `rlang::last_error()` to see where the error occurred.

**Comment by cqneosun** [comment]
> > wp2gene <- wp2gene %>% tidyr::separate(ont, c("name","version","wpid","org"), "%")
> > Error: object 'ont' not found
> > Run `rlang::last_error()` to see where the error occurred.

have you figure the error?I meet the same.

**Comment by droeatumn** [comment]
I never actually tested Sigit's suggestion. Should I reopen this issue?

**Comment by nyj123** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/61054316/113893347-80e3dd80-97f9-11eb-86bb-31c4923f23a6.png)

**Comment by Xiao-Zhong** [comment]
As above.
wp2gene <- wp2gene %>% tidyr::separate(ont, c("name","version","wpid","org"), "%")
Error: object 'ont' not found
Run `rlang::last_error()` to see where the error occurred.

**Comment by kroman4** [comment]
Hi, I ran into the same error with "ont". I changed "ont" to "term" because the column name in my gmt file is "term". This edit fixed the tidyr::separate code.
