### ISSUE TITLE
Run Human gene enrichGO return NA value on ONTOLOGY

### ISSUE THREAD

**Issue by honghh2018** [YuLab-SMU/clusterProfiler#249]
Hi YuLab, 
     Thank to develop the great tools for gene enrichment analysis.
      The human genes list was processed by R and than run the enrichment analysis by clusterProfiler's enrichGO function. nevertheless, when it run over, the data frame of result's column, 'ONTOLOGY', indicate NA values. The picture showing below:
     
![image](https://user-images.githubusercontent.com/41668708/76509986-d7160e00-648b-11ea-97fd-787fef5f0ebb.png)
   It was weird immensely that the result of enrichGO function just showing NA on BP and CC but MF.the picture showing below:
   
![image](https://user-images.githubusercontent.com/41668708/76510257-43910d00-648c-11ea-8449-57ffff94327f.png)

   Any comments would be appreciated
   Thanks

**Comment by honghh2018** [comment]
The clusterProfiler' s package detail displayed below:
Package: clusterProfiler
Type: Package
Title: statistical analysis and visualization of functional profiles
        for genes and gene clusters
Version: 3.14.2

**Comment by GuangchuangYu** [comment]
3.14.3 should fixed this.

**Comment by honghh2018** [comment]
Thanks for the urgent reply, I have fixed this problem following your prompting.
      On this case, if i want to draw the specific GO terms within the data frame of the outcome until the result was generated by enrichGO. how should i do to choose certain GO term to draw? 
The plot that i chose from enrichGO output's result to draw using ggplot2, it was ugly. and i hope can  use the function you was built-in.
       Thanks

**Comment by honghh2018** [comment]
![image](https://user-images.githubusercontent.com/41668708/76520730-6cba9900-649e-11ea-9980-f4360367a26f.png)

**Comment by GuangchuangYu** [comment]
you can past selected `DESCRIPTION` to `showCategory` parameter and it will do the trick.
