### ISSUE TITLE
Error:wrong orderBy parameter; set to default `orderBy = "x" when run dotplot

### ISSUE THREAD

**Issue by zhaoqingbo1993** [YuLab-SMU/clusterProfiler#251]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

**Comment by zhaoqingbo1993** [comment]
when I use the function "dotplot", it occurs that "wrong orderBy parameter; set to default `orderBy = "x" ",and the plot looks strange.

**Comment by GuangchuangYu** [comment]
duplicated. <https://github.com/YuLab-SMU/enrichplot/issues/22>.
