### ISSUE TITLE
Error: unused argument (eps = eps)

### ISSUE THREAD

**Issue by GMFranceschini** [YuLab-SMU/clusterProfiler#252]
Using `clusterProfiler_3.15.4` I get the following error after `GSEA(gene_list, TERM2GENE = t2g)` call. 

`
preparing geneSet collections...
GSEA analysis...
Error in fgsea(pathways = geneSets, stats = geneList, minSize = minGSSize,  : 
  unused argument (eps = eps)
`

I've tried to specify `eps` parameter manually to the default value, but it didn't help. `t2g` is a custom TERM2GENE dataframe. Please notice that before updating to the latest version of clusterProfiler I obtained the desired output. I think I will downgrade my version for the moment, but you might be interested in this issue.
Best regards

**Comment by GuangchuangYu** [comment]
If you use devel version of clusterProfiler, you need to also upgrade DOSE and fgsea.

**Comment by felipebatalini** [comment]
I am having the very same issue using clusterProfiler_3.14.3.

'Error in fgsea(pathways = geneSets, stats = geneList, minSize = minGSSize, : unused argument (eps = eps)'

Not sure how to fix this, would greatly appreciate help. Thanks!

**Comment by qins** [comment]
```
Error in .GSEA(geneList = geneList, exponent = exponent, minGSSize = minGSSize,  :
  unused argument (eps = eps)
```
not exactly same, but also `unused argument (eps = eps)`
