### ISSUE TITLE
'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'

### ISSUE THREAD

**Issue by alibumizj** [YuLab-SMU/clusterProfiler#256]
Hi，
This problem has only recently appeared.
Error in download.KEGG.Path(species) : 
  'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'
my scripts is this：
keggenrich <- enrichKEGG(gene = diffgeneID, universe = backgene, organism='human', keyType='ncbi-geneid,pvalueCutoff = 0.99,pAdjustMethod = "BH", minGSSize = 1, maxGSSize = 500,qvalueCutoff = 0.99,use_internal_data = FALSE)
Can you check for me please? Thank you in advance!
Best,
zhang

**Comment by alibumizj** [comment]
Sorry ,my scripts  organism='hsa' ,not is organism='human' ,I try to do that ,but not success.Thank you !

**Comment by 1tonsilla** [comment]
> Sorry ,my scripts organism='hsa' ,not is organism='human' ,I try to do that ,but not success.Thank you!

Hi，did you fix it already？I met the same problem..

**Comment by huerqiang** [comment]
This may be due to your internet speed problem, and are you using the latest version of clusterProfiler?

**Comment by 1tonsilla** [comment]
> This may be due to your internet speed problem, and are you using the latest version of clusterProfiler?

It's not about network access, because I can access the link through my browser. I use the latest version of R language and R studio, and then use this to get clusterprofiler：
“if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("clusterProfiler")”

I have searched, it seems that the version is too new, other aspects can not match, I tried to use R 3.6.0, but failed, after all, there is no R language foundation, I have gaven up, thank you for help!

**Comment by DamianFan** [comment]
is that because of my R version was too new? I faced the same problem. I could run GO Enrich package but failed to run KEGG package. How could I fix it?

**Comment by 1tonsilla** [comment]
> is that because of my R version was too new? I faced the same problem. I could run GO Enrich package but failed to run KEGG package. How could I fix it?

Maybe... now I use some online tools instead of R.   It is too difficult to fix the problem..

**Comment by DamianFan** [comment]
> > is that because of my R version was too new? I faced the same problem. I could run GO Enrich package but failed to run KEGG package. How could I fix it?
> 
> Maybe... now I use some online tools instead of R. It is too difficult to fix the problem..

Thank you for reply.
Can you tell my what online tool that you're using?

**Comment by 1tonsilla** [comment]
> > > is that because of my R version was too new? I faced the same problem. I could run GO Enrich package but failed to run KEGG package. How could I fix it?
> > 
> > 
> > Maybe... now I use some online tools instead of R. It is too difficult to fix the problem..
> 
> Thank you for reply.
> Can you tell my what online tool that you're using?

http://www.ehbio.com/ImageGP/
http://www.bioinformatics.com.cn/
have a try..

**Comment by ilee-ui** [comment]
my clusterProfiler version is 3.18.0.R version is 4.0.3.

**Comment by ilee-ui** [comment]
Error in download.KEGG.Path(species) : 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'
how to fix the issue?

**Comment by seashore001x** [comment]
I met the same problem

**Comment by GuangchuangYu** [comment]
should be fixed in v 3.18.1 (pls wait 2-3 days for bioconductor to update) and v 3.19.1 (currently on github).

Please try it.

**Comment by zym826** [comment]
I met the same problem.Did you solve it?

**Comment by mdtorohernando** [comment]
Hi! the same problem here: 

> kk_up = enrichKEGG(gene = gene_up, organism = 'mmu', pvalueCutoff = 0.05, qvalueCutoff = 0.05, use_internal_data = F)
Error in download.KEGG.Path(species) : 
  'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...

Cluster profiler v3.14.3
Rstudio v2021.09.0 build 351

**Comment by Cetus-1997** [comment]
> This may be due to your internet speed problem, and are you using the latest version of clusterProfiler?

I met the same problem. Is there any other solution?

**Comment by ilee-ui** [comment]
This is my solution:
```
install.packages("R.utils")
R.utils::setOption("clusterProfiler.download.method","auto")
```
enjoy !!!!

**Comment by Cetus-1997** [comment]
This question has puzzled me for three days. Thanks for your suggestion. It worked.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月8日 16:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [YuLab-SMU/clusterProfiler] 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html' (#256)


This is my solution:

install.packages("R.utils")

R.utils::setOption("clusterProfiler.download.method","auto")

enjoy !!!!

―

**Comment by slohr** [comment]
This issue seems to have returned for clusterProfiler 3.18.1 on R 4.0.5

I tried the solution that uses R.utils::setOption("clusterProfiler.download.method","auto")

However it still does not work.

```{r}
data(geneList, package='DOSE')
de <- names(geneList)[1:100]
yy <- enrichKEGG(de,pvalueCutoff=0.1)
head(yy)
```

Error in download.KEGG.Path(species) :
'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...
5.
stop("'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...")
4.
download.KEGG.Path(species)
3.
download_KEGG(species, KEGG_Type, keyType)
2.
prepare_KEGG(species, "KEGG", keyType)
1.
enrichKEGG(de, pvalueCutoff = 0.1)

Any suggestions?

**Comment by slohr** [comment]
I've narrowed it down to the internal functions kegg_link and kegg_list.

I don't have much more time to debug but if I patch with in-lined functions then I can get it to work again. Possibly a namespace issue?

Here's the patch:

```{r}
## https://www.genome.jp/kegg/rest/keggapi.html
## kegg_link('hsa', 'pathway')
ttp_kegg_link <- function(target_db, source_db) {
    url <- paste0("https://rest.kegg.jp/link/", target_db, "/", source_db, collapse="")
    local_mydownload <- function (url, method, quiet = TRUE, ...) 
    {
        if (capabilities("libcurl")) {
            dl <- tryCatch(utils::download.file(url, quiet = quiet, 
                method = "libcurl", ...), error = function(e) NULL)
        }
        else {
            dl <- tryCatch(downloader::download(url, quiet = TRUE, 
                method = method, ...), error = function(e) NULL)
        }
        return(dl)
    }
    local_kegg_rest <- function (rest_url) 
    {
        message("Reading KEGG annotation online:\n")
        f <- tempfile()
        dl <- local_mydownload(rest_url, destfile = f)
        if (is.null(dl)) {
            message("fail to download KEGG data...")
            return(NULL)
        }
        content <- readLines(f)
        content %<>% strsplit(., "\t") %>% do.call("rbind", .)
        res <- data.frame(from = content[, 1], to = content[, 2])
        return(res)
    }
    local_kegg_rest(url)
}

ttp_kegg_list <- function(db) {
    url <- paste0("https://rest.kegg.jp/list/", db, collapse="")
    local_mydownload <- function (url, method, quiet = TRUE, ...) 
    {
        if (capabilities("libcurl")) {
            dl <- tryCatch(utils::download.file(url, quiet = quiet, 
                method = "libcurl", ...), error = function(e) NULL)
        }
        else {
            dl <- tryCatch(downloader::download(url, quiet = TRUE, 
                method = method, ...), error = function(e) NULL)
        }
        return(dl)
    }
    local_kegg_rest <- function (rest_url) 
    {
        message("Reading KEGG annotation online:\n")
        f <- tempfile()
        dl <- local_mydownload(rest_url, destfile = f)
        if (is.null(dl)) {
            message("fail to download KEGG data...")
            return(NULL)
        }
        content <- readLines(f)
        content %<>% strsplit(., "\t") %>% do.call("rbind", .)
        res <- data.frame(from = content[, 1], to = content[, 2])
        return(res)
    }
    local_kegg_rest(url)
}

rlang::env_unlock(env = asNamespace('clusterProfiler'))
rlang::env_binding_unlock(env = asNamespace('clusterProfiler'))
assign('kegg_link', ttp_kegg_link, envir = asNamespace('clusterProfiler'))
assign('kegg_list', ttp_kegg_list, envir = asNamespace('clusterProfiler'))
rlang::env_binding_lock(env = asNamespace('clusterProfiler'))
rlang::env_lock(asNamespace('clusterProfiler'))
```
Then when I do this:

```{r}
data(geneList, package='DOSE')
de <- names(geneList)[1:100]
yy <- enrichKEGG(de, pvalueCutoff=0.1)
head(yy)
```

I get enrichment results:
df[6x9]

  | ID<chr> | Description<chr> | GeneRatio<chr> | BgRatio<chr> |  
-- | -- | -- | -- | -- | --
hsa04110 | hsa04110 | Cell cycle | 8/47 | 126/8157 |  
hsa04218 | hsa04218 | Cellular senescence | 7/47 | 156/8157 |  
hsa04114 | hsa04114 | Oocyte meiosis | 6/47 | 131/8157
...

Maybe this will help narrow it down.

**Comment by GuangchuangYu** [comment]
@slohr This is a known issue due to the recent update of KEGG. You need to upgrade clusterProfiler to the latest release version.

**Comment by GuangchuangYu** [comment]
Bioconductor is binding to a specific version of R. If you are using an old version of R, then you can't use the latest version of Bioconductor and there is no way to fix bugs for an old version of Bioconductor package.

**Comment by coffeeCowLu** [comment]
> @slohr This is a known issue due to the recent update of KEGG. You need to upgrade clusterProfiler to the latest release version.

version ‘4.4.4’ well done!

**Comment by shenzhongjun** [comment]
> This is my solution:
> 
> ```
> install.packages("R.utils")
> R.utils::setOption("clusterProfiler.download.method","auto")
> ```
> 
> enjoy !!!!

it still failed, I try `options(clusterProfiler.download.method = "wget")` and it worked. as 'utils::downloadfile' method has several download methods like “internal”、“wininet”（Windows only）、“libcurl”、“wget” and “curl”

**Comment by WellJoea** [comment]
you can set dowload method in innternal function like this:
```
        library(R.utils);
        kegg_link <- function (target_db, source_db) 
        {
            R.utils::setOption("clusterProfiler.download.method",'wget')
            options(clusterProfiler.download.method = "wget")
            getOption("clusterProfiler.download.method")

            url <- paste0("http://rest.kegg.jp/link/", target_db, "/", 
                source_db, collapse = "")
            print(url)
            clusterProfiler:::kegg_rest(url)
        }

        R.utils::setOption("clusterProfiler.download.method",'wget')
        options(clusterProfiler.download.method = "wget")
        getOption("clusterProfiler.download.method")
        reassignInPackage("kegg_link", pkgName="clusterProfiler", kegg_link)
```
