### ISSUE TITLE
enrichGO results (gene count) is not matching the expected gene count from the same database 

### ISSUE THREAD

**Issue by Monod79** [YuLab-SMU/clusterProfiler#259]
First I'd like to say that I love the output of ClusterProfiler. It's clear and intuitive, but I've stumble upon one problem... 

library(clusterProfiler)
library(org.Hs.eg.db)

### Here's a bunch of genes of interest
gene <- c(144568, 12, 1622, 22985, 58, 27245, 83543, 1646, 
          79087, 375, 378, 196528, 495, 513, 9774, 4076, 23581, 10421, 
          966, 55573, 1063, 134147, 1314, 1495, 28988, 1781, 9188, 9879, 
          1656, 140735, 8663, 3646, 8668, 1994, 2079, 23196, 2264, 2287, 
          2332, 10146, 27069, 8334, 8340, 11333, 3092, 3148, 9987, 1207, 
          1964, 8894, 1981, 3608, 3837, 8826, 6453, 29350, 5804, 3993, 
          23367, 3927, 27258, 51690, 92140, 8567, 4134, 9053, 4082, 23195, 
          55110, 126353, 5250, 9526, 4438, 51537, 283463, 727897, 56005, 
          7629, 4678, 31358, 55607, 4703, 9147, 25926, 4839, 10528, 1728, 
          100506658, 9885, 114882, 5036, 5062, 5116, 23244, 5159, 5297, 
          5411, 445582, 9588, 27339, 8899, 10594, 5692, 9991, 471, 5814, 
          7388, 5902, 9821, 5976, 729857, 55183, 6134, 6136, 6139, 6144, 
          6158, 6160, 6164, 494115, 10949, 6204, 6205, 6206, 6207, 6208, 
          6218, 6223, 6228, 6229, 6230, 6231, 6232, 51065, 6235, 6188, 
          6191, 6193, 6201, 51493, 6636, 6294, 9667, 84324, 4735, 10262, 
          54187, 9144, 9092, 6651, 55553, 117246, 89777, 6704, 6711, 6712, 
          6430, 8683, 2058, 23345, 10575, 10574, 7053, 10189, 3842, 9804, 
          8073, 9967, 57570, 9343, 8237, 9958, 23326, 8078, 9101, 23352, 
          84833, 10493, 3069, 494551, 128488, 30258, 8531, 563, 9189, 23099)

### The classic enrichGO query
x = enrichGO(gene, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "CC", maxGSSize = 1200, 
           qvalueCutoff = 0.01, pvalueCutoff = 0.05)

results <- x@result

### Here's the gene count of 'adherens junction' genes from the enrichgo output. There's 25 genes yay !
results.adherens.junction.gene <- subset(results, subset = results$Description == "adherens junction", select = "Count")

### Here's the expected gene count of 'adherens junction' genes extracted from the (org.Hs.eg.db) with the same list of genes. There's only 1 gene ???
gene.go.test <- bitr(gene, "ENTREZID", "GO", org.Hs.eg.db)
adherens.junction.gene.expected <- subset(gene.go.test, subset = GO == "GO:0005912", select = "ENTREZID")
length(adherens.junction.gene.expected)
  
Since there is only 1 adherens junction gene from my gene list that can be extracted from org.Hs.eg.db, how can enrichGO map 25 genes to the same GO term, using the same database and the same gene list? 

Thanks for your time!

Jonathan

**Comment by GuangchuangYu** [comment]
try:

```
gene.go.test <- bitr(gene, "ENTREZID", "GOALL", org.Hs.eg.db)
adherens.junction.gene.expected <- subset(gene.go.test, subset = GOALL == "GO:0005912", select = "ENTREZID")
nrow(adherens.junction.gene.expected)
```

**Comment by Monod79** [comment]
Thanks for the quick answer ! 

I now understand that enrichGO is using org.Hs.egGO2ALLEGS, which is much more inclusive than org.Hs.egGO. Is it possible to run enrichGO with org.Hs.egGO "GO" instead of org.Hs.egGO2ALLEGS "GOALL" ?

Jonathan
