### ISSUE TITLE
compareCluster - E coli K12 EnrichKegg error

### ISSUE THREAD

**Issue by pmt39** [YuLab-SMU/clusterProfiler#274]
Hello. I am using clusterProfiler R package. I am trying to make a visualize result using a dotplot graph for my data. It seems I am facing a stumbling block on the final analysis using compareCluster. I am working with E. coliK12 strain and I want to perform an enrichment analysis with Kegg (enrichKEGG) I wonder why my code is not working. The example of what I am trying to achieve is shown in this example link (https://yulab-smu.github.io/clusterProfiler-book/chapter11.html#formula-interface-of-comparecluster). Any ideas would be most appreciated. Thank you.

`mydf <- data.frame(Entrez=names(geneQ), FC=geneQ)`
`head(mydf)`
     
>           Entrez       FC
>     1    946671   7.1331936
>     2    947072   5.7164422
>     3    944863   5.4384038
>     4    945322   3.8615915
>     5    948027   3.7971514

```
mydf <- mydf[abs(mydf$FC) > 1,]
mydf$group <- "upregulated"
mydf$group[mydf$FC < 0] <- "downregulated"
mydf$othergroup <- "A"
mydf$othergroup[abs(mydf$FC) > 2] <- "B"
formula_res <- compareCluster(Entrez~group+othergroup, data=mydf, fun="enrichKEGG")
```
`**No enrichment found in any of gene cluster, please check your input...**
`

**Comment by huerqiang** [comment]
@pmt39 Your code is fine, but your data has no significant enrichment results。

**Comment by pmt39** [comment]
Thank you for taking the time. Much appreciated.

**Comment by goushixue** [comment]
You need to specify the species, there is a parameter `organism ` of the `enrichKEGG `function

**Comment by pmt39** [comment]
I see, I will try it in my codes then. Thank you for noting that. I hope it works :)
