### ISSUE TITLE
simplify function doesn't work

### ISSUE THREAD

**Issue by xiaoxiami105** [YuLab-SMU/clusterProfiler#278]
Dear Dr. Yu,

Thanks for providing the wonderful clusterprofiler. It helps me a lot.

Recently, I used the simplify function to simplify the result from compareCluster, but it didn't work (Before it worked normally).
The code I used to produce compareCluster result (this step worked well): 
DEGsBP <- compareCluster(DEGsIPA, fun="enrichGO",
                         OrgDb = org.Hs.eg.db,
                         keyType       = "ENTREZID",
                         ont           = "BP",
                         pAdjustMethod = "BH",
                         readable      = TRUE,
                         pvalueCutoff  = 0.05,
                         qvalueCutoff  = 0.05)

But when I try to simplify:
DEGsBPsim <- simplify(DEGsBP,cutoff=0.5,by="p.adjust",select_fun=min,measure = "Wang")

I got an error :
Error in simplify(DEGsBP, cutoff = 0.5, by = "p.adjust", select_fun = min,  : 
unused arguments (cutoff = 0.5, by = "p.adjust", select_fun = min, measure = "Wang")

**Comment by claraina** [comment]
I am having the same problem - getting the error "unused arguments (cutoff = 0.7, by = "p.adjust", select_fun = min)" even though it was working before. I don't think it's an issue with my enrich object (ego) as it is still showing the relevant GO Terms.

```
EEDDOC_ego <- enrichGO(gene = EEDDOC_gene.df$ENTREZID,
OrgDb = org.Mm.eg.db,
keyType = 'ENTREZID',
ont = "BP",
pAdjustMethod = "BH",
pvalueCutoff = 0.05,
qvalueCutoff = 0.05,
readable = TRUE)

sEEDDOC_ego <- simplify(EEDDOC_ego, cutoff=0.7, by="p.adjust", select_fun = min)

```

_Error in simplify(EEDDOC_ego, cutoff = 0.7, by = "p.adjust", select_fun = min) :
unused arguments (cutoff = 0.7, by = "p.adjust", select_fun = min)_

**Comment by huerqiang** [comment]
![image](https://user-images.githubusercontent.com/48857018/95683831-3d306280-0c20-11eb-8400-ec3860632625.png)
It works well.

**Comment by GuangchuangYu** [comment]
The error msg, `unused arguments`, indicates that you are using another `simplify()` function provided by other package. 

In this case, pls use `clusterProfiler::simplify()` to directly call the function provided by `clusterProfiler`.
