### ISSUE TITLE
enrichDGN failing to map gene ID

### ISSUE THREAD

**Issue by gitanjaliroy087** [YuLab-SMU/clusterProfiler#280]
I have a list of entrez gene ID's that is not mapping to enrichDGN. The below list is a small part of the list.

`test <- c("109676", "20254", "380684", "73094", "218038", "56013")`
`edo <- enrichDGN(test)`
`--> No gene can be mapped....
--> Expected input gene ID: 3119,5308,23633,4204,3805,4247
--> return NULL...`

What is the problem here?

**Comment by ccbvib** [comment]
I am experiencing the same issue. I have followed the vignette and constructed a sorted named vector with Entrez IDs, but none of the enrichment functions in clusterProfiler seem to accept this input.

str(geneList) # example gene list in vignette
Named num [1:12495] 4.57 4.51 4.42 4.14 3.88 ... - attr(*, "names")= chr [1:12495] "4312" "8318" "10874" "55143" ...

str(gene_list) # my gene list that I have constructed
 Named num [1:18907] 4.64 4.25 3.89 3.64 3.5 ... - attr(*, "names")= chr [1:18907] "13048" "100043108" "13099" "23850" ...

**Comment by GuangchuangYu** [comment]
If you check your ID in genbank, <https://www.ncbi.nlm.nih.gov/gene/109676>, you will find that the input IDs are belong to the species of mouse, while the `enrichDGN()` function expected gene IDs from human.

**Comment by ccbvib** [comment]
I am aware that my genes are from mice. That does not solve the underlying issue I am experiencing. For example, when I construct and specify a mouse universe I still get the same error as before:

```
--> No gene can be mapped....
--> Expected input gene ID: 627,2130,462,50484,144811,7283
--> return NULL...

## construct mouse universe (list of Entrez ids) 
read.csv("./results.csv", header = TRUE, row.names = 1) %>%
  mutate(ENTREZID = mapIds(org.Mm.eg.db, gene, "ENTREZID", "ENSEMBL") %>%
  unname()) %>% dplyr::filter(!is.na(ENTREZID)) %>% dplyr::select(ENTREZID) -> mouse_universe
head(mouse_universe)
ENTREZID
1    14679
2    54192
3    12544
4    14955
5   107815
6    11818

## construct gene list
stat_gene_list <- (res$stat)
names(stat_gene_list) <- res$ENTREZID
gene_list <- stat_gene_list[order(stat_gene_list, decreasing = TRUE)]
de <- names(gene_list)[abs(gene_list) > 2]
head(de)
# [1] "13099"     "228911"    "259302"    "74051"     "100043108" "269587"   

## the list of ENTREZIDs is in the mouse universe
head(de %in% mouse_universe$ENTREZID)
[1] TRUE TRUE TRUE TRUE TRUE TRUE

## but enrichDGN does not work even when I specify a mouse universe. why?
edo <- DOSE::enrichDGN(gene = de,
                       pvalueCutoff = 0.05,
                       universe = mouse_universe$ENTREZID,
                       minGSSize = 30,
                       maxGSSize = 500)
```

**Comment by ccbvib** [comment]
My question is, what is the format (in terms of data structures) that DOSE::enrichDGN() accepts for the "universe" parameter? Your documentation does not specify what types inputs are accepted, it only says "background genes." Is it a list of character strings? A vector of integers? Any help is appreciated.

**Comment by huerqiang** [comment]
This has nothing to do with "universe" parameter. your error is because the annotation data of enrichDGN is only applicable to humans.

**Comment by JingrenZhong** [comment]
Dear professor Yu, recently I am using gseKEGG to run my differential genes, but came accross with this no mapping problem. Even there isn't any example after "Expected input gene ID: "

I prepared the gene list and run it as shown, and the list actually worked well with gseGO function (no replicates and NA in the list, and geneid is ENTREZID). May I ask what could the problem be? Could it be an internet problem...? Thank you so much for your help in advance!

#preparation of gene list:

original_gene_list <- diff_genes$log2FoldChange
names(original_gene_list) <- diff_genes$geneid
gene_list = sort(original_gene_list, decreasing = TRUE)

#runing gesKEGG:
kk2 <- gseKEGG(geneList     = gene_list,
               organism     = "ssc",
               nPerm        = 10000,
               minGSSize    = 3,
               maxGSSize    = 800,
               pvalueCutoff = 0.05,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")


#runing results -----------------------------------------

preparing geneSet collections...
--> Expected input gene ID: 
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....
