### ISSUE TITLE
setReadable() on compareClusterResult for enrichKEGG

### ISSUE THREAD

**Issue by hreinwal** [YuLab-SMU/clusterProfiler#281]
Dear Guangchuang,

first of all thank you for your amazing tool. I am having a similar issue as described in #126, but in my case I am running the `enrichKEGG` within the `compareCluster` function. Hence the solution from #126 does not work as `enrichKEGG` does not support the parameter `readable`. 
`kegg <- compareCluster(ls.ora, organism = "dre", keyType = "ncbi-geneid", fun = 'enrichKEGG',  universe = univ.entrez)`

So I tried to convert the ENTREZIDs with `setReadable` but I get an error telling me that this function only supports `enrichResults `or `gseaResults `as input. In this case the input is as `compareClusterResults` object. 
`kegg <- setReadable(kegg, OrgDb = org.Dr.eg.db, keyType = "ENTREZID")`
`Error in setReadable(kegg, OrgDb = org.Dr.eg.db, keyType = "ENTREZID") : 
  input should be an 'enrichResult' or 'gseaResult' object...`

Is there any workaround for that or a particular reason why `compareClusterResults` are not supported by the function?

**Comment by MikaQiao** [comment]
I met the same problems, looking forward to the answer.

**Comment by huerqiang** [comment]
@MikaQiao Please use the latest version of DOSE

**Comment by MikaQiao** [comment]
Thanks you very much for your repIy. have the DOSE v3.14.0 package, and I also update my clusterProfiler v3.16.1. still the problem happens. When I run compareCluster with setReadable = T, it remind me Error in fun(i, ...) : unused argument (setReadable = TRUE).

**Comment by GuangchuangYu** [comment]
@MikaQiao latest github version. not latest release version.

By the end of this month, the github version will become a new release version.

**Comment by MikaQiao** [comment]
Got it, Thanks a lot!
