### ISSUE TITLE
How to extract genes from particular GO-Term or Biological Pathway?

### ISSUE THREAD

**Issue by claraina** [YuLab-SMU/clusterProfiler#288]
Hello, 
I am wondering how to get the list of genes grouped in a particular GO-Term of Biological Pathway. I have an enrichGO output, which I've also used the simplify function on. From this result, I've into a bar plot (attached). For example, my top enriched pathway is T cell activation, how do I obtain the genes which have been grouped into this pathway? Thanks kindly.

<img width="360" alt="bar plot" src="https://user-images.githubusercontent.com/68907502/88922942-3eeeb900-d2b4-11ea-8818-1f84a868968f.PNG">

**Comment by Ning-L** [comment]
Hi, if you take a look at the enrichGO output (an S4 object), you'll find a slot called "result" which is a data.frame containing the detailed enrichment results, you can use `@` to access the slot, example :
![image](https://user-images.githubusercontent.com/31008500/93669812-fde67a00-fa96-11ea-93c8-516ba3059a81.png)

**Comment by claraina** [comment]
@Ning-L Apologies for the late reply, but thank you for this! Your code worked like a charm.
