### ISSUE TITLE
A problem in the clusterProfile-book

### ISSUE THREAD

**Issue by shangguandong1996** [YuLab-SMU/clusterProfiler#293]
Hi, Dear developer
I found in the Chapter 5 Gene Ontology Analysis 5.1 Supported organisms, there is a sentence

> If user have GO annotation data (in data.frame format with **first column of gene ID and second column of GO ID**), they can use enricher() and gseGO() functions to perform over-representation test and gene set enrichment analysis.

and
> If genes are annotated by direction annotation, it should also annotated by its ancestor GO nodes (indirect annation). If user only has direct annotation, they can pass their annotation to buildGOmap function, which will infer indirection annotation and generate a data.frame that suitable for both enricher() and gseGO().

which means the buildGOmap can directly ouput the input of enricher. But I found the **the first column of buildGOmap output df** is **GO**, and the second column is **gene**, accoring to the source code of buildGOmap

```
buildGOmap <- function(gomap) {

    ## remove empty GO annotation
    gomap <- gomap[gomap[,1] != "", ]
    
    Gene2GO <- split(as.character(gomap[,1]), as.character(gomap[,2]))
    
    Gene2ALLGO <- lapply(Gene2GO,
                         function(i) {
                             mfans <- unlist(mget(i, GOMFANCESTOR, ifnotfound=NA))
                             bpans <- unlist(mget(i, GOBPANCESTOR, ifnotfound=NA))
                             ccans <- unlist(mget(i, GOCCANCESTOR, ifnotfound=NA))
                             ans <- c(mfans, bpans, ccans)
                             ans <- ans[ !is.na(ans) ]
                             ans <- c(i, ans)
                             ans <- unique(ans)
                             ans <- ans[ans != "all"]
                             return(ans)
                         })

    go2gene <- stack(Gene2ALLGO)
    colnames(go2gene) <- c("GO", "Gene")
    
    return(go2gene)
}
```

So I am a little confused about the input df column order of enricher

Best wishes
Guandong Shang

**Comment by GuangchuangYu** [comment]
try it and you will find that there is no problem.

**Comment by shangguandong1996** [comment]
Thanks for your reply :) Uncle Y.
But I just found in Chapter 3 
> clusterProfiler provides enricher function for hypergeometric test and GSEA function for gene set enrichment analysis that are designed to accept user defined annotation. They accept two additional parameters TERM2GENE and TERM2NAME. As indicated in the parameter names, **TERM2GENE is a data.frame with first column of term ID and second column of corresponding mapped gene** and TERM2NAME is a data.frame with first column of term ID and second column of corresponding term name. TERM2NAME is optional.

And If I input change the ontology df order, there will be error information
```
library(magrittr)
library(clusterProfiler)

data(geneList, package="DOSE")
gene <- names(geneList)[abs(geneList) > 2]

wpgmtfile <- system.file("extdata/wikipathways-20180810-gmt-Homo_sapiens.gmt", package="clusterProfiler")
wp2gene <- read.gmt(wpgmtfile)
wp2gene <- wp2gene %>% tidyr::separate(ont, c("name","version","wpid","org"), "%")
wpid2gene <- wp2gene %>% dplyr::select(wpid, gene) #TERM2GENE
wpid2name <- wp2gene %>% dplyr::select(wpid, name) #TERM2NAME


> wpid2gene <- wpid2gene[, c(2,1)]
> ewp <- enricher(gene, TERM2GENE = wpid2gene, TERM2NAME = wpid2name)
--> No gene can be mapped....
--> Expected input gene ID: WP3969,WP2643,WP399,WP4205,WP2064,WP4262
--> return NULL...

```



Please forgive me if I misunderstand something. And Thanks again for powerful clusterProfiler and the matching book :)

Best wishes
Guandong Shang

**Comment by GuangchuangYu** [comment]
new book website, <https://yulab-smu.top/biomedical-knowledge-mining-book/>.

**Comment by shangguandong1996** [comment]
Thanks :)
