### ISSUE TITLE
Fail to make enrichment map

### ISSUE THREAD

**Issue by helenysl** [YuLab-SMU/clusterProfiler#299]
Hi, I was able to make enrichment map a few weeks ago with emapplot function, but recently it seems to be broken?

It used to work when I tried:
`emapplot(ego_up, pie_scale=1.5,layout='kk')`
but now the error occur:
`Error in emapplot.enrichResult(x, showCategory = showCategory, color = color,  : 
  unused argument (pie_scale = 1.5)`

and when I tried:
`emapplot(ego_up,layout='kk')`

`Error in has_pairsim(x) : 
  Term similarity matrix not available. Please use pairwise_termsim function to deal with the results of enrichment analysis.`

so does 
`emapplot(ego_up)`

`Error in has_pairsim(x) : 
  Term similarity matrix not available. Please use pairwise_termsim function to deal with the results of enrichment analysis.`

Any suggestion? Thank you.

**Comment by huerqiang** [comment]
We have updated the `emapplot` function. Please use `?emapplot`  and `?pairwise_termsim` to view the latest documents.
`pie_scale` parameter has been changed to `node_scale`.

**Comment by helenysl** [comment]
Ok, thanks!
Btw, did you also update the GO database version? My enriched GO terms became different using the same input.

**Comment by huerqiang** [comment]
This should be because you also updated the annotation packages on Bioconductor.

**Comment by helenysl** [comment]
Excuse me, one more question. The enrichResult object now seems to be empty.
I'd like to get an enriched gene list under a specific GO term, but nothing appeared.

**Comment by huerqiang** [comment]
Please provide a repeatable code.



At 2020-11-06 17:18:15, "Helen Lin" <notifications@github.com> wrote:

Excuse me, one more question. The enrichResult object now seems to be empty.
I'd like to get an enriched gene list under a specific GO term, but nothing appeared.

**Comment by denoqo** [comment]
It seem still no working with the `node_scale` and `line_scale`.

`Error in emapplot.compareClusterResult(x, showCategory = showCategory,  : unused argument (line_scale = 0.1)`
