### ISSUE TITLE
Enable cache of KEGG database 

### ISSUE THREAD

**Issue by gaospecial** [YuLab-SMU/clusterProfiler#306]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

`clusterProfiler` download KEGG annotation every time when running functions such as `enrichKEGG()`. This setting is of course benificial for using the most recent annotation, but has some disadvantages. First of all, the database is generally stable and will not changed day by day. Secondly, the http request sent by these functions is frequently out of service due to connection and/or database overload. At least I have encounter such error and found those functions give unpredicated errors, #305 as an example. 

Therefore, I suggest to enable cache of KEGG database in the future version of `clusterProfiler`.

**Comment by huerqiang** [comment]
@gaospecial enrichKEGG can use the cache. After downloading the annotation data once, if R is not closed, the last cached data can be used when running again. For each species, we need to download the corresponding KEGG annotation data, So it may not be suitable to store them all in the R package.

**Comment by shenshen-wu** [comment]
Here are the solution to the network. We can download the special data we need and use it offline.

https://wemp.app/posts/5463eab7-6ec7-44a0-adf9-7e3baae22361

**Comment by gaospecial** [comment]
> Here are the solution to the network. We can download the special data we need and use it offline.
> 
> https://wemp.app/posts/5463eab7-6ec7-44a0-adf9-7e3baae22361

`createKEGGdb` is what I want.
