### ISSUE TITLE
Is there any way to install a previous version of ```clusterProfiler``` package?

### ISSUE THREAD

**Issue by jxshi** [YuLab-SMU/clusterProfiler#323]
Hi @GuangchuangYu ,

I am currently using the [bcbioRNASeq](https://github.com/hbc/bcbioRNASeq) pipeline to do some RNAseq data analysis. However, the recent version of ```bcbioRNASeq``` encountered some minor issues due to the incompatibility with the latest version of ```clusterProfiler```. I have checked the ```tags``` and [Bioconductor clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html) main page and was not able to find an older version of it.
Is there any way I can install an older version (3.17.5 or earlier version) of ```clusterProfiler```?

Thank you in advance!
Best,
Jianxiang

**Comment by GuangchuangYu** [comment]
install a corresponding (old) version of R as Bioconductor is stick to specific R version.
