### ISSUE TITLE
How to filter S4 object to plot a subset of enriched terms with heatplot

### ISSUE THREAD

**Issue by ZheFrench** [YuLab-SMU/clusterProfiler#324]
```
genes.enriched.GO_mf <- enricher(genes, TERM2GENE=GO_mfterm2gene, TERM2NAME=GO_mfterm2name,pvalueCutoff = 0.05,pAdjustMethod = "BH",minGSSize = 10,maxGSSize = 500, qvalueCutoff = 0.05)

heatplot(genes.enriched.GO_mf)+ theme(  axis.text.y = element_text( size = 12))
```

But imagine you want to  plot specific  Goterms of your choice not the whole object in the set.
heatplot need  a S4 object. How to get a subset of genes.enriched.GO_mf  for specific terms.
It's harrder to filter than a simple dataframe...

**Comment by huerqiang** [comment]
Please tyr:
```r
 heatplot(genes.enriched.GO_mf, showCategory = Your_selectd_GOterms)
```
For example:
```r
selected <- c("mitotic nuclear division", "mitotic sister chromatid segregation", "chromosome segregation")
heatplot(genes.enriched.GO_mf, showCategory = selected)
```

**Comment by ZheFrenchKitchen** [comment]
You saved my fucking Day ! Thanks a lot !!!!!

**Comment by ZheFrenchKitchen** [comment]
I reopen the issue just to check something.
For dotplot showCategory use a number to plot ten best enriched terms using padj. There is no way to pass a list of specitic terms as heatplot.

`dotplot(formula_res, x=~geneslist,showCategory=10) + ggplot2::facet_grid(~cellline)  + scale_fill_viridis(option="B",direction = -1)`

**Comment by GuangchuangYu** [comment]
works in a similar way for `dotplot`.
