### ISSUE TITLE
Use compareCluster with enricher

### ISSUE THREAD

**Issue by ZheFrenchKitchen** [YuLab-SMU/clusterProfiler#326]
`
print(Reactome.listing)
$h4.genes.1A.2A
   [1] "AASS"               "ABC7-42404400C24.1" "ABCA13" ...
$h4.genes.1B.2B
   [1] "ACO1"        "ACPP"        "ADAMTS1"     "ADAMTS3"     "ADCY3" ...

ck <- compareCluster(geneCluster = Reactome.listing, fun =  enricher(., TERM2GENE=Reactome, TERM2NAME=NA,pvalueCutoff = 0.05,pAdjustMethod = "BH",minGSSize = 10,maxGSSize = 500, qvalueCutoff = 0.05))
`

I saw that fun can be used with  "groupGO", "enrichGO", "enrichKEGG", "enrichDO" or "enrichPathway" .
Is that possible to use custom enricher ? 

What do you set for genes list  ?

**Comment by ZheFrenchKitchen** [comment]
`ck <- compareCluster(geneCluster = Reactome.listing, fun =  "enricher",TERM2GENE=Reactome, TERM2NAME=NA,pvalueCutoff = 0.05,pAdjustMethod = "BH",minGSSize = 10,maxGSSize = 500, qvalueCutoff = 0.05)
`
Ok found it by myself. Can be useful for others.

**Comment by JulieBaker1** [comment]
> `ck <- compareCluster(geneCluster = Reactome.listing, fun = "enricher",TERM2GENE=Reactome, TERM2NAME=NA,pvalueCutoff = 0.05,pAdjustMethod = "BH",minGSSize = 10,maxGSSize = 500, qvalueCutoff = 0.05) ` Ok found it by myself. Can be useful for others.

There are no quotes for the fun parameter. That is to say, the right writing is as below
ck <- compareCluster(geneCluster = Reactome.listing, fun = enricher,TERM2GENE=Reactome, TERM2NAME=NA,pvalueCutoff = 0.05,pAdjustMethod = "BH",minGSSize = 10,maxGSSize = 500, qvalueCutoff = 0.05)
