### ISSUE TITLE
How to view non-significant pathways in clusterProfiler?

### ISSUE THREAD

**Issue by gaospecial** [YuLab-SMU/clusterProfiler#328]
在做基于 KEGG 数据库的代谢通路富集分析或 GSEA 分析后，可以得到显著的通路。不知道那些不显著的通路，如何进行查看？

之所以想了解这些信息，是想评估代谢通路整体上受影响的程度有多大。例如总共有 200 条代谢途径，其中有 10 条显著变化。或者可以根据情况说，氨基酸代谢相关通路受影响比较大，而糖代谢相关通路不受影响。或者说同化途径受影响，能量代谢异常等。

**Comment by GuangchuangYu** [comment]
你为什么不pvalueCutoff=1, qvalueCutoff=1, 出来结果后，as.data.frame呢？

**Comment by gaospecial** [comment]
> 你为什么不pvalueCutoff=1, qvalueCutoff=1, 出来结果后，as.data.frame呢？

这个机智的回答让我茅塞顿开，感觉似乎还可以从 KEGG.db 入手。我是不是想错了？

**Comment by NeginValizadegan** [comment]
Hi all,

I set a specific q value but the results still shows all of it. Why is that?

**Comment by gaospecial** [comment]
> Hi all,
> 
> I set a specific q value but the results still shows all of it. Why is that?

You'd bettern open a new issue and paste your reproducible example on it.
