### ISSUE TITLE
gsePathway geneList input

### ISSUE THREAD

**Issue by Jcerra7** [YuLab-SMU/clusterProfiler#333]
Hello! I am trying to run a Pathway GSEA, but have been facing issues with the correct formatting of the geneList argument. Through the Biomedical Knowledge Mining using GOSemSim and clusterProfiler page I have followed the code below from section 9.3 to recreate the example. This genelist dataset has gene names and p scores and upon running the following code I get the error output:

data("geneList")

#Pathway GSEA
y <- gsePathway(geneList, 
                pvalueCutoff = 0.2,
                pAdjustMethod = "BH", 
                verbose = FALSE)

Error in GSEA_internal(geneList = geneList, exponent = exponent, minGSSize = minGSSize,  : 
  geneList should be a decreasing sorted vector...

I have tried using geneList <- sort(geneList, decreasing = TRUE) before running the above code but get this error:

Error in check_gene_id(geneList, geneSets) : --> No gene can be mapped....

Any information regarding the proper formatting of this aspect of the geneList argument would be great. Thanks in advance.

**Comment by huerqiang** [comment]
You may have used `geneList` data from other packages,  please try
```r
data(geneList, package = "DOSE")
#Pathway GSEA
library(ReactomePA)
y <- gsePathway(geneList,
pvalueCutoff = 0.2,
pAdjustMethod = "BH",
verbose = FALSE)
```

**Comment by Jcerra7** [comment]
Yes! Thank you. Code is functioning now.
