### ISSUE TITLE
The values of pvalue and padjust in the legend are both displayed as 0 using gseaplot2 function(,pvalue_table = T)

### ISSUE THREAD

**Issue by muchangqing777** [YuLab-SMU/clusterProfiler#335]
Hello professor, I am using your package for _GSEA_ analysis. 
When I used the _gseaplot2_ function to visualize the results, I encountered some problems with the legend display of _pvalue_ and _p.adjust_ ._The values of _pvalue_ and _padjust_ in the legend_ are both displayed as 0.

Below is my _data_:
[genelist.txt](https://github.com/YuLab-SMU/clusterProfiler/files/6571202/genelist.txt)

Below is my _code:_

        library("clusterProfiler")
        setwd("C:/Users/12578/Desktop/")
        rt=read.table("genelist.txt",sep="",header=T,check.names=F)

        geneFC=rt$logFC
        gene <- rt$all.gene
        names(geneFC)=gene
        geneList <- sort(geneFC,decreasing = TRUE)

        gsego<- gseGO(geneList     = geneList,
                                   OrgDb        = org.Hs.eg.db,
                                   keyType="SYMBOL",
                                   ont          = "ALL",
                                   minGSSize    = 15,
                                   maxGSSize    = 500,
                                   eps = 0,
                                   pvalueCutoff = 0.05,
                                   verbose      = FALSE)

         library(enrichplot)
         gseaplot2(gsego, geneSetID = 1, 
                           title = gsego$Description[1],pvalue_table = TRUE)

The error of the plot I made included is below:

![KCM@TKQ29BR@W5Y%J2% G@U](https://user-images.githubusercontent.com/85098989/120159095-69d4d100-c227-11eb-94e1-aedec38d4064.png)

I don't know why the values are both 0.
Please let me know how can I solve this problem so that the plot can display true values and whether it is a problem with which parameter setting.
I am a Chinese student, my English is not very good, forgive me.I hope my questioning process meets your expectations.
Thanks!
Mu Changqing

**Comment by huerqiang** [comment]
This is not a mistake, gseaplot2 will hold only four decimal places, and if the p value is very small, it will be displayed as 0.

**Comment by GuangchuangYu** [comment]
@huerqiang maybe we should support scientific notation.

**Comment by huerqiang** [comment]
OK, I will update the `gseaplot2` later.
