### ISSUE TITLE
Problem of dotplot

### ISSUE THREAD

**Issue by zenglongjin** [YuLab-SMU/clusterProfiler#352]
Dear Yu
When I use function of dotplot for compareCluster' result, the error exhibits：
Error: Aesthetics must be valid data columns. Problematic aesthetic(s): colour = p.adjust. 
Did you mistype the name of a data column or forget to add after_stat()?
But it was fine before. Thank you very much

**Comment by huerqiang** [comment]
Please give the data and code, and I'll test it for you.

**Comment by zenglongjin** [comment]
When I restart computer, the error was missing. Thank you very much------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月26日(星期一) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuLab-SMU/clusterProfiler] Problem of dotplot (#352)
