### ISSUE TITLE
compareCluster error

### ISSUE THREAD

**Issue by saisaitian** [YuLab-SMU/clusterProfiler#353]
![image](https://user-images.githubusercontent.com/26356557/127663941-da779f9e-4b04-490a-bb7b-8ffef0a92230.png)
![image](https://user-images.githubusercontent.com/26356557/127664087-d1289c2e-0e41-4a99-a8b7-4e6ae72e738b.png)

Dear author:
 I have two groups,but it always get one sample result, how to fix it?

**Comment by huerqiang** [comment]
@saisaitian You should check your enrichment result `formula_res`, maybe only genes belonging to "A" can be significantly enriched in the KEGG pathways.

**Comment by saisaitian** [comment]
You are corrected,but how can I fix it?

**Comment by saisaitian** [comment]
When I use compareCluster for GO analysis，how can I do only in BP terms? I do not find related parameters

**Comment by GuangchuangYu** [comment]
@saisaitian  pass `ont = 'BP'` to `compareCluster()`.
