### ISSUE TITLE
The meaning of minGSSize?

### ISSUE THREAD

**Issue by endlessbeloved** [YuLab-SMU/clusterProfiler#356]
```R
# this is my code
ekk <- enricher(gene=row.names(diff_gene_deseq2), pvalueCutoff = 1, pAdjustMethod = "BH",
+                 TERM2GENE = pathway2gene,TERM2NAME = pathway2name
+                 ,minGSSize = 1,
+                 maxGSSize = 500)
```
if I use  minGSSize=1 , maxGSSize = 500 ,I got 17 ekk_result in total.

if I use minGSSize=1 , maxGSSize = 50, I got 3 ekk_result in total.
if I use minGSSize=50 , maxGSSize = 500, I got 19 ekk_result in total.

I feel confused about the results.
Should't the final result of  1 to 50 + the final result of  50 to 500  = the final result of  1 to 500??
but 3+19 != 17 
I don't know why the result unequal.

**Comment by huerqiang** [comment]
Maybe you should add `qvalueCutoff = 1` to check whether "the final result of 1 to 50 + the final result of 50 to 500 = the final result of 1 to 500". Your results were screened by "qvalueCutoff", and it was normal that they don't add up.

**Comment by endlessbeloved** [comment]
wow!!! 
awesome!!
That is the qvalue

> Maybe you should add `qvalueCutoff = 1` to check whether "the final result of 1 to 50 + the final result of 50 to 500 = the final result of 1 to 500". Your results were screened by "qvalueCutoff", and it was normal that they don't add up.
Awesome!!
When I set `qvalueCutoff = 1` , it works!!
Many thanks
