### ISSUE TITLE
使用conda安装后无法使用

### ISSUE THREAD

**Issue by WZo0o** [YuLab-SMU/clusterProfiler#359]
Y叔您好！
请问我在服务器上使用conda创造了一个虚拟环境后，使用conda成功安装了clusterprofiler，但是在后续的使用过程中，却无法导入clusterprofiler，一直出现如下报错。

 library(clusterProfiler)

Error: package or namespace load failed for ‘clusterProfiler’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/lustre/inspur/software/Rlibrary-4.0.0/igraph/libs/igraph.so':
  libRlapack.so: cannot open shared object file: No such file or directory

请问该如何解决这种报错呢？

**Comment by GuangchuangYu** [comment]
> unable to load shared object '/lustre/inspur/software/Rlibrary-4.0.0/igraph/libs/igraph.so':

这还不够清楚么？用Linux理应会看报错信息，并知道该怎么去解决它。

**Comment by WZo0o** [comment]
ok
