### ISSUE TITLE
关于enrichKEGG函数提供离线模式的建议

### ISSUE THREAD

**Issue by Liripo** [YuLab-SMU/clusterProfiler#360]
`enrichKEGGD`的参数`use_internal_data = T`使用了KEGG.db包，而设置FALSE时，从kegg api获取，能否外置个参数自己提供从kegg api下载好路径,方便离线模式使用最新的数据呢？

**Comment by huerqiang** [comment]
你可以按照这个教程里使用`createKEGGdb`来生成本地的KEGG.db包：
https://mp.weixin.qq.com/s/PwrdQAkG3pTlwMB6Mj8wXQ

**Comment by GuangchuangYu** [comment]
本地用`enricher`不香吗？
