### ISSUE TITLE
Is it possible to generate cnetplot with my own set of data

### ISSUE THREAD

**Issue by Riverhuang42** [YuLab-SMU/clusterProfiler#362]
Hi there, 

![image](https://user-images.githubusercontent.com/45997340/130385188-686c6847-9727-4d3f-a633-82eb8f6c62c8.png)
I have the go-term analysis result ready as shown above. I wonder whether I can generate centplot with the dataframe I have.
I tried with these code, but it didnt work. what should I do to make it happen? Thanks a lot.
> goterm<- read.delim("gobp_de.txt", header=T)
> cnetplot(goterm,colorEdge=TRUE)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘cnetplot’ for signature ‘"data.frame"’
>

**Comment by GuangchuangYu** [comment]
see <https://yulab-smu.top/biomedical-knowledge-mining-book/enrichplot.html#fig:cnetplotgeneral>.

**Comment by GuangchuangYu** [comment]
you need to install the github version of `enrichplot`.
