### ISSUE TITLE
gene Set size

### ISSUE THREAD

**Issue by yx-xu** [YuLab-SMU/clusterProfiler#365]
Dear author:
Thanks for your powerful packages! 
I have met a question about gene set  size, i think it may be refer to your aiming gene site, isn't it? 
But when I use 625 gene to enricher, i got "No gene set have size > 10 ", when I change parameter "minGSSize = NA", got same result also; But when set "maxGSSize = NA" or "maxGSSize = 100000" or "maxGSSize = 10000", I got diifferent result.
so what does "gene Set size" really means? if it means input gene set, should the reslut of  "maxGSSize = 100000" be same as "maxGSSize = 10000" ??
Looking forward to your reply, Thank you very much!

![image](https://user-images.githubusercontent.com/57080322/131523839-44433690-238c-4109-aefe-7258889d0aa6.png)

**Comment by huerqiang** [comment]
Please see #356

**Comment by yx-xu** [comment]
Thanks for your help! I had seen this before, but i did not set this parameter,so in my command it should all be the default 0.2, i think the key of my question is not this. could you see it again? Thanks a lot!

![image](https://user-images.githubusercontent.com/57080322/131526672-73045715-e4f1-454d-9e6e-913fbd2c01b2.png)

**Comment by huerqiang** [comment]
This should be because the number of genes in your gene set(t2gja) is all larger than 700. 
try : `sum(table([t2gja, 1]) < 700)`

**Comment by yx-xu** [comment]
Yes! 
so this "gene set size" refer to the number of genes correspond to per GO, right?

Thanks for your help~~


![image](https://user-images.githubusercontent.com/57080322/131595608-975e2322-aa13-406e-b6fb-f0648285683b.png)

**Comment by huerqiang** [comment]
Yes.
