### ISSUE TITLE
Ridgeplot showing different results!

### ISSUE THREAD

**Issue by GACGAMA** [YuLab-SMU/clusterProfiler#367]
I'm using ClusterProfiler for expression comparation between two groups, using NOISEQ rank (related to Log2FC, same direction).

When using GSEA:
library(ReactomePA)

```
kk2 <- gsePathway(resultados_deseq, 
                  pvalueCutoff = 0.05,
                  pAdjustMethod = "BH", 
                  verbose = FALSE)
head(kk2)

```
and then plotting:

`p3 <- ridgeplot(kk2, , orderBy="NES") + labs(x = "enrichment distribution")`

I get:
![chrome_3iA0g0wYdG](https://user-images.githubusercontent.com/30120425/131713127-eb210f6f-7a69-47aa-820f-6c082f9a4cc0.png)

![chrome_Q6rDOCeLx0](https://user-images.githubusercontent.com/30120425/131713134-6965a831-9b0e-4971-9063-04098a4cf2aa.png)

But the results are very different in ridgeplot than in the S4 object (the enrichment score values - NES - are different in the graph than in the results)! How can I correct this and how should I interpret the enrichment score is this case?

**Comment by huerqiang** [comment]
@GACGAMA  How can you get the enrichment score from `ridgeplot` graph? And why do you say the result is wrong? Please give a detailed reason.

**Comment by GACGAMA** [comment]
@huerqiang hello! I've been using the ridge plot as described in the vignette, item 15.9 "ridgeline plot for expression distribution of GSEA result". 
I created the Reactome GSEA with clusterprofiler and used the function ridgeplot on the object created by clusterProfiler. But the Enrichment Score Values in the results object (kk2) are different than in the graph produced with ridgeplot function. I expected NES or ES values, as seen in the table (both have positive and negative values), but the values for enrichment score in the ridgeplot varies from 0.8 to 1.0, which are not the same as the results that produced the plot. This is different than dotplot, which is giving the exact same results as seen in the objects created by clusterprofiler.

**Comment by huerqiang** [comment]
@GACGAMA  "Maybe the values in the X axis is another value but not enrichment score?" You are right. The X axis of

**Comment by huerqiang** [comment]
@GACGAMA `Maybe the values in the X axis is another value but not enrichment score?` Your are right. The X axis of `ridgeplot` graph is your input value(e.g., NOISEQ rank or logFC), not ES.  And the Y axis is the frequency of the values. So you can get the distribution of genes' "NOISEQ rank"  in each pathway.
