### ISSUE TITLE
dotpot()函数size参数所支持表示的变量是否可以优化得更灵活一些，而不仅仅是:one of“geneRatio”，“Percentage”and“count”?

### ISSUE THREAD

**Issue by Chao-Guo-hub** [YuLab-SMU/clusterProfiler#370]
在我使用ClusterProfiler时，对于compareCluster的结果，通过mutate添加了FoldEnrichment一项，但是使用dotplot时，并不能通过将size参数调整为FoldEnrichment而进行这一项的可视化，但是我试了普通的GO或者KEGG富集结果是可以的，所以希望在后续优化中可以使得dotplot()函数各项参数所支持的变量更灵活一些~

**Comment by GuangchuangYu** [comment]
should be supported in the recent version of `enrichplot`.

**Comment by GuangchuangYu** [comment]
@huerqiang pls make sure.

**Comment by huerqiang** [comment]
We have solved it in https://github.com/YuLab-SMU/enrichplot/pull/144.
