### ISSUE TITLE
Can't update package to 4.0.5

### ISSUE THREAD

**Issue by GuoYu-Peng** [YuLab-SMU/clusterProfiler#371]
Hello, I want to update clusterProfiler to >=4 version. I am using system R.  
My command is:  
```R
BiocManager::install("clusterProfiler", force = TRUE)
``` 

The error is:
```R
* installing *source* package ‘clusterProfiler’ ...                                           
** using staged installation                                                                  
** R                                                                                          
** data                                                                                       
** inst                                                                                       
** byte-compile and prepare package for lazy loading              
Error: object ‘get_fun_from_pkg’ is not exported by 'namespace:rvcheck'
Execution halted                                                                              
ERROR: lazy loading failed for package ‘clusterProfiler’ 
```

My R:
```R
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.3                         
year           2020                        
month          10                          
day            10                          
svn rev        79318                       
language       R                           
version.string R version 4.0.3 (2020-10-10)
nickname       Bunny-Wunnies Freak Out 
```

What can I do to solve this problem? Thanks a lot.

**Comment by huerqiang** [comment]
The `get_fun_from_pkg` function had been moved from `rvcheck` to `yulab.utils`. You can install the development version of `clusterProfiler`, it should be OK :
```r
if(!requireNamespace("remotes", quietly = TRUE))
    install.packages("remotes")
remotes::install_github("YuLab-SMU/clusterProfiler")
```

**Comment by svillicana** [comment]
Hi. After trying to install from git, I get this error:
`* installing *source* package ‘clusterProfiler’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘enrichplot’ 1.6.1 is being loaded, but >= 1.9.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘clusterProfiler’`

Then, if try to install `enrichplot` with `remotes::install_github("YuLab-SMU/enrichplot")`, I get:
`* installing *source* package ‘enrichplot’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘get_aes_var’ is not exported by 'namespace:rvcheck'
Execution halted
ERROR: lazy loading failed for package ‘enrichplot’`

Here is my `sessionInfo()`:
`R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    usethis_2.0.1     devtools_2.4.2    pkgload_1.2.2     R6_2.5.1          rlang_0.4.11     
 [8] fastmap_1.1.0     tools_3.6.1       pkgbuild_1.2.0    sessioninfo_1.1.1 cli_3.0.1         withr_2.4.2       ellipsis_0.3.2   
[15] remotes_2.4.0     rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.5.2    purrr_0.3.4       callr_3.7.0      
[22] fs_1.5.0          ps_1.6.0          testthat_3.0.4    curl_4.3.2        memoise_2.0.0     glue_1.4.2        cachem_1.0.6     
[29] compiler_3.6.1    desc_1.3.0        prettyunits_1.1.1`

Thanks.

**Comment by svillicana** [comment]
Hi. After trying to install from git, I get this error:
```R
* installing *source* package ‘clusterProfiler’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘enrichplot’ 1.6.1 is being loaded, but >= 1.9.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘clusterProfiler’
```

Then, if try to install `enrichplot` with `remotes::install_github("YuLab-SMU/enrichplot")`, I get:
```R
* installing *source* package ‘enrichplot’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: object ‘get_aes_var’ is not exported by 'namespace:rvcheck'
Execution halted
ERROR: lazy loading failed for package ‘enrichplot’
```

Here is my `sessionInfo()`:
```R
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   magrittr_2.0.1    usethis_2.0.1     devtools_2.4.2    pkgload_1.2.2     R6_2.5.1          rlang_0.4.11     
 [8] fastmap_1.1.0     tools_3.6.1       pkgbuild_1.2.0    sessioninfo_1.1.1 cli_3.0.1         withr_2.4.2       ellipsis_0.3.2   
[15] remotes_2.4.0     rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1      processx_3.5.2    purrr_0.3.4       callr_3.7.0      
[22] fs_1.5.0          ps_1.6.0          testthat_3.0.4    curl_4.3.2        memoise_2.0.0     glue_1.4.2        cachem_1.0.6     
[29] compiler_3.6.1    desc_1.3.0        prettyunits_1.1.1
```

Thanks.

**Comment by svillicana** [comment]
I solved it. I had to install manually `ggtree` and `yulab.utils`. Thanks.

**Comment by GuangchuangYu** [comment]
there still maybe compatible issues among pkgs.

A better solution is to upgrade your R and install latest release of `clusterProfiiler` via `BiocManager::install()`.

**Comment by musaidris** [comment]
same here .. happened after updating many packages ..

library(clusterProfiler)
Error: package or namespace load failed for ‘clusterProfiler’:
 object ‘get_fun_from_pkg’ is not exported by 'namespace:rvcheck'
In addition: Warning message:
package ‘clusterProfiler’ was built under R version 4.0.2 9

installing ggtree and yulab.utils didn't solve the problem, 

problem also not solved by: 
if(!requireNamespace("remotes", quietly = TRUE))
    install.packages("remotes")
remotes::install_github("YuLab-SMU/clusterProfiler")

**Comment by adRn-s** [comment]
Hi, I believe that staying on the development versions is less than ideal but so far, for many users at our institute the only option was to install package, and dependencies, manually with:

```
remotes::install_github('YuLab-SMU/ggtree')
remotes::install_github('YuLab-SMU/gosemsim')
remotes::install_github("YuLab-SMU/enrichplot")
remotes::install_github("YuLab-SMU/clusterProfiler")
```

I help with the administration of a rstudio server at a research institution, and everyone asks me about installing clusterProfiler. It's happened 3-4 times in the current year. The first time, using R 4.2.1, I told a PhD student to downgrade ggplot2. That worked allright, but far from ideal.

Would you consider adding these instructions in your readme? Maybe under "Installing development versions". I'm yet to try if instead of install_github, BiocManager (going one by one) also works.

**Comment by mmokrejs** [comment]
Hi,
  I also was asked to install an "old" software based on R-3.4.4 requiring `clusterprofiler` and likewise am facing

```
trying URL 'https://bioconductor.org/packages/3.8/bioc/src/contrib/clusterProfiler_3.10.1.tar.gz'
Content type 'application/octet-stream' length 4163560 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

* installing *source* package ‘clusterProfiler’ ...
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'get_fun_from_pkg' not found
Error : unable to load R code in package ‘clusterProfiler’
ERROR: lazy loading failed for package ‘clusterProfiler’
* removing ‘/home/bionic/R/x86_64-pc-linux-gnu-library/3.5/clusterProfiler’
```

```
> BiocManager::install(c("tibble","ggtree","yulab.utils", version = 3.7, force = TRUE))
Bioconductor version 3.8 (BiocManager 1.30.22), R 3.5.3 (2019-03-11)
Installing package(s) 'ggtree', '3.7', 'TRUE'
trying URL 'https://bioconductor.org/packages/3.8/bioc/src/contrib/ggtree_1.14.6.tar.gz'
Content type 'application/octet-stream' length 5852027 bytes (5.6 MB)
==================================================
downloaded 5.6 MB

* installing *source* package ‘ggtree’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : object ‘get_aes_var’ is not exported by 'namespace:rvcheck'
ERROR: lazy loading failed for package ‘ggtree’
* removing ‘/home/bionic/R/x86_64-pc-linux-gnu-library/3.5/ggtree
```

Which versions of the sufficiently old `rvcheck`, `ggtree`, `tidytree`, `treeio`, `yulab.utils` should I install and from where? Thank you.
