### ISSUE TITLE
Could it be possible to add one option in enrichplot::treeplot?

### ISSUE THREAD

**Issue by yingzhang121** [YuLab-SMU/clusterProfiler#390]
I have used treeplot to plot pathway similarities. However, the tip label (pathway names) is usually too long  to read (because it extends into the clade label). One way to resolve this issue is to allow customized size of tip labels. By looking into the code, I believe this could be done by modify the "group_tree" function, where the function of "geom_tiplab" is called. If the "size" option is allowed, modify tip labels will be much easier.

Best,
Ying

**Comment by GuangchuangYu** [comment]
@huerqiang do we support wrapping text into multiple lines for tip labels of treeplot?

**Comment by huerqiang** [comment]
Currently, the tip labels do not support being wrapped into multiple lines, and only cluster labels are supported. I will enable it in the next version.
