### ISSUE TITLE
Error in h(simpleError(msg, call)) : error in evaluating the argument 'envir' in selecting a method for function 'mget': object 'org.Mm.egSYMBOL2EG' not found

### ISSUE THREAD

**Issue by XiaohanLuDuke** [YuLab-SMU/clusterProfiler#396]
_Code I ran as below and the error happened._

enes =as.vector(modelX[,1])
entrezIDsPT <- mget(genes, org.Mm.egSYMBOL2EG, ifnotfound=NA )
entrezIDsPT <-as.character(entrezIDsPT)
modelX=cbind(modelX,entrezID=entrezIDsPT)
write.table(modelX,file="modelX_gene.txt", sep="\t", quote=F, row.names=F)

_

Error in h(simpleError(msg, call)) : error in evaluating the argument 'envir' in selecting a method for function 'mget': object 'org.Mm.egSYMBOL2EG' not found

_

_Waiting for some suggestion online now, appreciate it!!!_

**Comment by XiaohanLuDuke** [comment]
_I ran:_ 

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("org.Mm.eg.db")

_But error said:_ 

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.2 (2021-11-01)
Warning: package(s) not installed when version(s) same as current; use `force = TRUE` to re-install: 'org.Mm.eg.db'

What should I do? Please give your suggestions if you know how to fix the issue. 
Thanks!

**Comment by huerqiang** [comment]
Your issue has nothing to do with clusterProfiler, and you can get help from Google.
1. "object 'org.Mm.egSYMBOL2EG' not found": Obviously, you don't have this environmental object.
2. "Warning: package(s) not installed when version(s) same as current; use force = TRUE to re-install: 'org.Mm.eg.db'": You have already installed this package.

**Comment by XiaohanLuDuke** [comment]
> Your issue has nothing to do with clusterProfiler, and you can get help from Google.
> 
> 1. "object 'org.Mm.egSYMBOL2EG' not found": Obviously, you don't have this environmental object.
> 2. "Warning: package(s) not installed when version(s) same as current; use force = TRUE to re-install: 'org.Mm.eg.db'": You have already installed this package.

Thank you so much. I have this issue resolved.
