### ISSUE TITLE
Can't remove line in treeplot 

### ISSUE THREAD

**Issue by SynatKeam** [YuLab-SMU/clusterProfiler#399]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

Dear Professor, 

sorry to post my question here because i cannot solve it via Biostar / Bioconductor. 

I am using treeplot to visualize my enrichment plot and would like to remove the line in the plot as shown in the attached file. Do you have a moment to help me out. I really appreciate your help.

![treeplot](https://user-images.githubusercontent.com/86950372/143734609-5f5d5f67-d72b-4625-b504-0887b2c8878e.JPG)

Here is my code 
```

library(enrichplot)

edox2 <- pairwise_termsim(ego3)

treeplot(edox2, hclust_method = "average", nWords=0)

```

Kind Regards,

synat,

**Comment by huerqiang** [comment]
At present, we do not provide the parameter of removing lines. And it looks like your picture is incomplete, missing the part on the right.
![image](https://user-images.githubusercontent.com/48857018/143804014-37f49ab3-ddcb-428b-8265-f782821e7002.png)

**Comment by SynatKeam** [comment]
Thank you so much, Professor. 

Kind Regards,

Synat

**Comment by benjibromberg** [comment]
@SynatKeam,

You can use scale_x_break(c(numeric_1, numeric_2) from the ggbreak package (see [https://yulab-smu.top/treedata-book/faq.html#shrink-outlier-long-branch](https://yulab-smu.top/treedata-book/faq.html#shrink-outlier-long-branch))
