### ISSUE TITLE
How to create an enrichment map with the returned clusterProfiler GSEA results using enrichmentMap app in Cytoscape?

### ISSUE THREAD

**Issue by lincj1994** [YuLab-SMU/clusterProfiler#401]
Hi. Thanks for your effort in developing clusterProfiler. I want to know how to create an enrichment map with the returned clusterProfiler GSEA results using enrichmentMap app in Cytoscape? It seems that the returned results of GSEA should be reformatted for use with enrichmentMap.

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/DOSE/wiki/using-cytoscape-to-visualize-enrichMap-produced-by-DOSE-clusterProfiler-ReactomePA>.
