### ISSUE TITLE
Assigning objects to GO environment 

### ISSUE THREAD

**Issue by Nelson-Gon** [YuLab-SMU/clusterProfiler#403]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))

Unfortunately it may not be easily possible to create a reproducible example. However, when using `gseGO`, sometimes the function will error with 
>object GO2ONT not found

A similar error message can be found at https://www.biostars.org/p/9481469/ which again just magically disappeared.

I think this is to do with the assignment part, where objects are assigned into "GO_ENV". 
```
assign("GO2ONT", goOnt, envir = GO_DATA)
```
I have further tracked down this bug to this line:

```
if (ont == "ALL") {
    res <- add_GO_Ontology(res, GO_DATA)
  }
```
If one sets `ont` to `BP` for instance, it all works fine. 
What I would have loved would be for it to be possible to have an idea of where this `GO2ONT` is saved to better track why it does not exist. Simply reinstalling the package/updating `fgsea` seems to have fixed the issue. Also, perhaps it would be great to have some kind of verbose message (that could be turned off for those who do not need it) showing what is happening at this stage.  

* [x] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

**Comment by huerqiang** [comment]
Please provide a reproducible example with this error, This will provide us with great convenience in solving it.

**Comment by Nelson-Gon** [comment]
Well, it works sometimes, and sometimes does not. I think it may be hard to reproduce this and will close this issue.
