### ISSUE TITLE
How are the GSEA results ordered? The terms are not ordered by ES/NES/p/q/padj or any column

### ISSUE THREAD

**Issue by jordan129** [YuLab-SMU/clusterProfiler#408]
Dear Prof. Yu and colleagues,

ClusterProfiler is great. I just have a few quick questions. How are the GSEA results ordered? This is useful to know if the top terms in the excel file are more enriched or important in the experiment.

In addition, what does the "rank" of the term mean? How are the padj and q value calculated?

![image](https://user-images.githubusercontent.com/40268980/144932124-b94204b3-704d-495b-84cc-2dee4b17e786.png)

Many thanks!

**Comment by huerqiang** [comment]
The  GSEA results are ordered by `pvalue`.
`rank` means the position of max runningScore(enrichmentScore >= 0) or min runningScore(enrichmentScore < 0).
The p.adjust and qvalue are calculated by `p.adjust` and qvalue::qvalue, respectively.

**Comment by jordan129** [comment]
> The GSEA results are ordered by `pvalue`. `rank` means the position of max runningScore(enrichmentScore >= 0) or min runningScore(enrichmentScore < 0). The p.adjust and qvalue are calculated by `p.adjust` and qvalue::qvalue, respectively.

Thanks Erqiang for your quick reply!

Since there are so many same p values (in my current dataset, the top 46 terms have the same p value), it seems I need to pick up interested terms to plot. Currently, for the terms with same p value, they are ordered by the term ID. I re-ordered it by NES.

Thanks again for your help!

**Comment by GuangchuangYu** [comment]
@huerqiang we should make it as default. 

1. sorted by `p.adjust`
2. if `p.adust` is identical, sorted by `abs(NES)`.

**Comment by GuangchuangYu** [comment]
<https://github.com/YuLab-SMU/DOSE/commit/751ca5f0d48736dbfe419677a87f3793e2736192>

**Comment by JiahuaQu** [comment]
Hi,
In my gseGO output table, 
(1) the column of rank does not look like ranked by p.adjust
(2) the top ranked rows have the tags=100% while some with no gene in the core_enrich column
![image](https://github.com/YuLab-SMU/clusterProfiler/assets/57730598/75d091d8-d79e-4dae-86a2-31f1dca48cde)

**Comment by huerqiang** [comment]
@JiahuaQu Please provide your R object of enrichment result , not just a table in excel.

**Comment by JiahuaQu** [comment]
> @JiahuaQu Please provide your R object of enrichment result , not just a table in excel.
Sure. Please help check the attached rds zip as well as the exported table. Thank you very much.
[BP.csv](https://github.com/YuLab-SMU/clusterProfiler/files/11554216/BP.csv)
[BP.zip](https://github.com/YuLab-SMU/clusterProfiler/files/11554219/BP.zip)

**Comment by huerqiang** [comment]
> The GSEA results are ordered by `pvalue`. `rank` means the position of max runningScore(enrichmentScore >= 0) or min runningScore(enrichmentScore < 0). The p.adjust and qvalue are calculated by `p.adjust` and qvalue::qvalue, respectively.

@JiahuaQu There's nothing wrong with your results, as I described.

**Comment by JiahuaQu** [comment]
> > The GSEA results are ordered by `pvalue`. `rank` means the position of max runningScore(enrichmentScore >= 0) or min runningScore(enrichmentScore < 0). The p.adjust and qvalue are calculated by `p.adjust` and qvalue::qvalue, respectively.
> 
> @JiahuaQu There's nothing wrong with your results, as I described.

Hi, can you help explain more about the runninhScore you meant? I'm still confused what the values in the column of rank mean and how we can use them. Thank you

**Comment by huerqiang** [comment]
Pleae see the code of rank value:
```r
    rank <- sapply(observed_info, function(x) {
        runningES <- x$runningES
        ES <- x$ES
        if (ES >= 0) {
            rr <- which.max(runningES$runningScore)
        } else {
            i <- which.min(runningES$runningScore)
            rr <- nrow(runningES) - i + 1
        }
        return(rr)
    })
```

**Comment by JiahuaQu** [comment]
> Pleae see the code of rank value:
> 
> ```r
>     rank <- sapply(observed_info, function(x) {
>         runningES <- x$runningES
>         ES <- x$ES
>         if (ES >= 0) {
>             rr <- which.max(runningES$runningScore)
>         } else {
>             i <- which.min(runningES$runningScore)
>             rr <- nrow(runningES) - i + 1
>         }
>         return(rr)
>     })
> ```

Got it. Thank you so much.
Can you also help check why there are the empty lists of genes in the last column, core_enrichment?
