### ISSUE TITLE
Error in eval(parse(text = fun)) : object 'enrichDO' not found

### ISSUE THREAD

**Issue by Sophia409** [YuLab-SMU/clusterProfiler#412]
Hello,

enrichDO didn't work on my dataset, but "enrichGO", "enrichKEGG", and "enrichPathway" can work normally. What's the possible reason?

> # KEGG
> formula.KEGG <- compareCluster(ENTREZID~cluster, data=mouse_specific_genesClusterDF,
                                fun='enrichKEGG', organism='mouse')
> # DO
> formula.DO <- compareCluster(ENTREZID~cluster, data=mouse_specific_genesClusterDF,
                                fun='enrichDO', organism='mouse')
Error in eval(parse(text = fun)) : object 'enrichDO' not found

**Comment by huerqiang** [comment]
```r
library(DOSE)
```
