### ISSUE TITLE
Function "enrichGO()" output a null object, function "gseGO()" output gseaResult contains no gene ratio.

### ISSUE THREAD

**Issue by CoreyChen95** [YuLab-SMU/clusterProfiler#413]
Hi, the team of "clusterProfiler"

I'm new to clusterProfiler, still in the process of getting my hands-on how to work with the package. I've recently encountered a problem with the function "enrichGO()". I've created a numeric vector containing all my significant genes named with gene symbols (gene names). And when I try to try to perform the GO gsea with the function "enrichGO()" with the following codes, it output null with no warning and errors in the console:
`gseEG=enrichGO(gene=gene_list, OrgDb = org.Hs.eg.db,universe = names(gene_list), ont='ALL', pvalueCutoff = 0.1, keyType = 'SYMBOL', pAdjustMethod = "BH", readable = TRUE)`

Another question is, when I performed the GO gsea with the function "gseGO()", with the same numeric vector mentioned above, the gseaResult that it outputed contains no generatio data, is that normal? Or the "gseGO()" function naturally doesn't output generatio data?

Thank you so much in advance for answering my questions!

**Comment by GuangchuangYu** [comment]
no `geneRatio` reported in GSEA result.

**Comment by CoreyChen95** [comment]
> 

Thank you so much for answering my question prof Yu. Regarding the "enrichGO()"  question, is there any previous record of a similar issue? It would be awesome if you can also help me out with the "enrichGO()" question. Thank you!

**Comment by GuangchuangYu** [comment]
there is no result with your current settings, (e.g., pvalueCutoff, etc.).
