### ISSUE TITLE
Genes missing in gseKEGG test?

### ISSUE THREAD

**Issue by jytan01** [YuLab-SMU/clusterProfiler#414]
Hello,

Thank you very much for your tool.
I am using the gseKEGG function to test for KEGG pathway enrichment in my set of mouse genes (please see attached). 

```
library(clusterProfiler)
library(enrichplot)

test.dat <- read.table( file="TNvsST_GAN_25.FC.geneList.sig.txt", header=F, sep="\t", stringsAsFactors = F, quote="\"" )
test.dat.t <- t(test.dat)
colnames(test.dat.t) <- test.dat.t[1,]
test.dat.t <- test.dat.t[-1,]

gse.test <- gseKEGG(geneList=test.dat.t, 
             organism = "mmu", 
             keyType = "kegg", 
             nPerm = 10000, 
             pvalueCutoff = 0.05,
             pAdjustMethod = "BH" )

ridgeplot(gse.test, showCategory = 50) + labs(x = "enrichment distribution")
```
[TNvsST_GAN_25.FC.geneList.sig.txt](https://github.com/YuLab-SMU/clusterProfiler/files/7775824/TNvsST_GAN_25.FC.geneList.sig.txt)

However, it appears that some genes annotated in specific pathways are not accounted for in the enrichment test? For example, I am looking specifically at genes in the Arachidonic Acid (AA) Metabolism pathway (KEGG id: mmu00590). This is the output from gseKEGG:

```
> gse.kegg.TRAUT.sig[30]

               ID                 Description setSize enrichmentScore       NES       pvalue   p.adjust     qvalues rank                  leading_edge
mmu00590 mmu00590 Arachidonic acid metabolism      41      -0.4544566 -2.261911 0.0003261579 0.00282174 0.001728508  633 tags=44%, list=9%, signal=40%
                                                                                                             core_enrichment
mmu00590 13850/13109/69836/13110/13117/72082/100040843/13099/107141/13118/277753/13095/13119/13096/75512/433247/404195/13088
```

While genes listed here (13850/13109/69836...) are annotated in the AA pathway, there are a few other AA genes that are in the data set but not listed here (i.e. Pla2g4a(18783), Alox5(11689), Cyp5(21391)).

I would greatly appreciate if you can help me clarify this issues.

Many thanks and best wishes,
Jennifer

**Comment by huerqiang** [comment]
The result only lists the core enriched genes of mmu00590, not all the genes that annotated in the pathway.
