### ISSUE TITLE
dotplot ERROR: 'x' is NULL so the result will be NULL

### ISSUE THREAD

**Issue by frylhc** [YuLab-SMU/clusterProfiler#429]
Hi Dr. Yu,
    I am running GO enrichment of an non-model organism using the enricher function of clusterProfiler. For the sake of limited gene number (91 genes) of the target gene set, I did not do multiple correction test and thus set the pAdjustMethod parameter to “none”. I checked the enrichment results, and it informed me that several GO terms were significantly enriched according to the pvalue. BUT, when I visiualized the results using dotplot function in enrichplot package, the following error occured. I am perplexed. What could the possible reason for the error? And what should I do if I just want to visualize the result using pvalue < 0.05 as a cutoff? 
Best!
Fu

`>enrich.m30.BP <- enricher(m30,TERM2GENE=go.background.BP,TERM2NAME=go,pvalueCutoff=0.05,pAdjustMethod = "none")
> dotplot(enrich.m30.BP,x="GeneRatio",color="pvalue")
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
In addition: Warning message:
In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL`

![image](https://user-images.githubusercontent.com/68120639/152909395-eab9328d-f379-4bde-aee6-057b7d6b78c8.png)

**Comment by huerqiang** [comment]
@frylhc Could you please provide your data `enrich.m30.BP`:
```r
save(enrich.m30.BP, file = "enrich.m30.BP.Rdata")
```
Or you can try:
```r
enrichplot::dotplot(enrich.m30.BP,x="GeneRatio",color="pvalue")
```

**Comment by frylhc** [comment]
I have tried the code, and the error still occured. I made a reproducible example of the enrich.m30.BP, it can be found in the URL: https://gist.github.com/frylhc/9ce75b3e7ff204be11f779e4634afa73. Thank a lot!
Best,
Fu

**Comment by frylhc** [comment]
Dear Dr. Hu,
The RData file are appended in the attachment. Thanks.
Best,
Fu

从 Windows 版邮件发送

发件人: Erqiang Hu
发送时间: 2022年2月8日 12:03
收件人: YuLab-SMU/clusterProfiler
抄送: frylhc; Mention
主题: Re: [YuLab-SMU/clusterProfiler] dotplot ERROR: 'x' is NULL so theresult will be NULL (Issue #429)

@frylhc Could you please provide your data enrich.m30.BP:
save(enrich.m30.BP, file = "enrich.m30.BP.Rdata")
Or you can try:
enrichplot::dotplot(enrich.m30.BP,x="GeneRatio",color="pvalue")
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huerqiang** [comment]
@frylhc 
There are no significantly enriched results when you use the default qvalueCutoff :
```r
> dim(enrich.m30.BP)
[1] 0 9
```
If you want to visualize the result with the cutoff of pvalue < 0.05, you should add the parameter `qvalueCutoff = 1`:
```r
enrich.m30.BP <- enricher(m30,TERM2GENE=go.background.BP,
    TERM2NAME=go,pvalueCutoff=0.05, qvalueCutoff = 1,
    pAdjustMethod = "none")
```

**Comment by frylhc** [comment]
Dear Dr. Hu,

I suppose that when I set pAdjustMethod to none, the quevalueCutoff won't be taken into consideration. Now I get the idea. Thanks a lot for your quick reply. 

Best, 
Fu

**Comment by frylhc** [comment]
Hi Dr. Hu,

I have tried your suggestion, but the produced results by dotplot function makes no difference. Here below is my code and the produced plot. In object "aa" and "bb", I have set the qvalueCutoff to "1" and the default(0.02), respectively, but the produced plots are the same.

`aa <- enricher(gene.list.m30,TERM2GENE=go.background.BP,TERM2NAME=go,pvalueCutoff=0.05,pAdjustMethod = "none",qvalueCutoff = 1)
bb <- enricher(gene.list.m30,TERM2GENE=go.background.BP,TERM2NAME=go,pvalueCutoff=0.05,pAdjustMethod = "none")
p1 <- dotplot(aa,showCategory=15,color="pvalue")
p2 <- dotplot(bb,showCategory=15,color="pvalue")
cowplot::plot_grid(p1,p2,ncol=2,lebels=c("qvalueCutoff=1","qvalueCutoff=default(0.2)"))`

![aa](https://user-images.githubusercontent.com/68120639/153532874-1bfe73c7-2377-4af7-a390-1527cb635cdb.jpg)


Besides, when I compare the enrichment results from object "aa" and "bb" using "aa@result" and "bb@result", I found that setting qvalueCutoff makes no difference, for "aa@result" and "bb@result" are the same. But when I output the results using "write.xlsx" function in R package "openxlsx", several enrichment results from object "aa" or "bb" is lost. What could be the possible reason for this?

**Comment by huerqiang** [comment]
@frylhc 
(1) aa@result and bb@result should be same, because they are not filtered by `qvalueCutoff`. This parameter only works in `as.data.frame`, `dim` and other similar functions.
(2) `dotplot` only visualization the enrichment result that meet a certain threshold(aa@qvalueCutoff, aa@pvalueCutoff), it is possible that after filtering, the two results are the same.
(3) I think it has anything to do with `openxlsx`. Did you use `as.data.frame()`  to extract enrichment results? The `as.data.frame`  function only keeps results that satisfy the threshold.

**Comment by frylhc** [comment]
Dear Dr Hu，

Now I fully understand. Thanks a lot.

Best,
Fu
