### ISSUE TITLE
treeplot visulization 

### ISSUE THREAD

**Issue by BhardwajArch** [YuLab-SMU/clusterProfiler#432]
![treeplot_group3](https://user-images.githubusercontent.com/95864186/153863414-b85c69b8-b4c4-48e8-ba14-58ec40c96f6e.png)
Hello 

I would like to display my enrichment result with treeplot.  

  formula_res <- compareCluster(listInput,  fun="enrichGO", OrgDb = org.Hs.eg.db)
    test.out <- enrichplot::pairwise_termsim(formula_res)
   edox2 <- pairwise_termsim(test.out)
  treeplot(edox2, font.size=1) + scale_y_discrete(labels=function(x) str_wrap(x, width=20))

But gene ontology terms are not visible in the "treeplot". I tried different setting i.e different font.size but still getting same output. 
I would appreciate all the suggestions.

**Comment by huerqiang** [comment]
@BhardwajArch You can adjust the values of `offset`, `offset_tiplab`, and `hexpand`.
