### ISSUE TITLE
dotplot function with a compareClusterResult object leads to the plot being generated automatically, even if the result is assigned to a variable.

### ISSUE THREAD

**Issue by jimrperkins** [YuLab-SMU/clusterProfiler#443]
Using the dotplot function with a compareClusterResult object leads to the plot being generated automatically, even if the result is assigned to a variable.

Compare the behaviour with dotplot using an enrichResult:

```
library(clusterProfiler)
library(DOSE)
data(geneList)
de <- names(geneList)[1:100]
x <- enrichDO(de)

dotplot(x) # Makes plot
ee <- dotplot(x) # Doesn't make plot.
```

However, the following leads to a plot in both cases. I understand that this should only happen in the second case.

```
data(gcSample)
xx <- compareCluster(gcSample, fun="enrichKEGG",
                          organism="hsa", pvalueCutoff=0.05)
dotplot(xx) # makes plot
ff <- dotplot(xx) # also makes plot - I believe it shouldn't - this would be in line with the rest of the enrichplots.
```

Looking at the code, I wonder if the last line of one of the functions under dotplot needs a return()

**Comment by GuangchuangYu** [comment]
thanks to <https://github.com/YuLab-SMU/enrichplot/pull/160>. The behavior is now identical.

**Comment by jimrperkins** [comment]
Perfect. I assume this has not been patched to the Bioconductor release, so I should install from github to obtain this fix?

**Comment by huerqiang** [comment]
@jimrperkins Currently we need to use the  Github version.
