### ISSUE TITLE
Pvalues‘ calculation are based on which method?(chisq? bino-test? or other method?) 

### ISSUE THREAD

**Issue by shelfey** [YuLab-SMU/clusterProfiler#444]
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and followed the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure you are using the latest release version
	* [ ] read the [documentation](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [ ] google your quesion/issue

### Describe your issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what you expected and what actually happened)

### Ask in the right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with the tag `clusterProfiler`

**Comment by GuangchuangYu** [comment]
<https://yulab-smu.top/biomedical-knowledge-mining-book/enrichment-overview.html#ora-algorithm>
