### ISSUE TITLE
How to show gene name（symbol） in cnetplot（）

### ISSUE THREAD

**Issue by zwyxxx** [YuLab-SMU/clusterProfiler#446]
How to show gene name（symbol） in cnetplot（）

my cnetplot can only show geneID but not symbol

Thanks！
<img width="216" alt="捕获" src="https://user-images.githubusercontent.com/102456005/160269100-c534bc7c-4689-4dbf-9060-97dd2399eeb0.PNG">

**Comment by GuangchuangYu** [comment]
[duplicated](https://github.com/YuLab-SMU/clusterProfiler/issues/447)
