### ISSUE TITLE
How to show gene name（symbol） in cnetplot（） when using compareCluster（）

### ISSUE THREAD

**Issue by zwyxxx** [YuLab-SMU/clusterProfiler#447]
<img width="216" alt="捕获" src="https://user-images.githubusercontent.com/102456005/160269144-714bb98f-c983-4da0-a6ec-5d55dd774b83.PNG">

**Comment by GuangchuangYu** [comment]
see <https://yulab-smu.top/biomedical-knowledge-mining-book/useful-utilities.html#setReadable>

**Comment by zwyxxx** [comment]
> see https://yulab-smu.top/biomedical-knowledge-mining-book/useful-utilities.html#setReadable

Thanks!
