### ISSUE TITLE
enrichGO  throws an error if readable is true

### ISSUE THREAD

**Issue by ikohane** [YuLab-SMU/clusterProfiler#449]
I am calling enrichGO using a vector of gene symbols. It runs smoothly as shown below. However if I specify readable=TRUE (see further below) it reports an error: 

### Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]

I do not understand the reason for the error.

Thanks for any clarification.

-Zak

> enrich <-
+     enrichGO(
+         gene = genes,
+         OrgDb = org.Hs.eg.db,
+         keyType = 'SYMBOL',
+         ont = "MF",
+         pAdjustMethod = "BH",
+         pvalueCutoff  = 0.01,
+         qvalueCutoff  = 0.01)
> enrich
#
# over-representation test
#
#...@organism 	 Homo sapiens 
#...@ontology 	 MF 
#...@keytype 	 SYMBOL 
#...@gene 	 chr [1:2802] "MTND1P23" "MTND2P28" "MTCO1P12" "MTCO2P12" "MTATP6P1" "PLEKHN1" "RP11-54O7.17" "HES4" "ISG15" "TNFRSF18" "TNFRSF4" "SDF4" "ACAP3" ...
#...pvalues adjusted by 'BH' with cutoff <0.01 
#...23 enriched terms found
'data.frame':	23 obs. of  9 variables:
 $ ID         : chr  "GO:0008009" "GO:0003735" "GO:0042287" "GO:0042379" ...
 $ Description: chr  "chemokine activity" "structural constituent of ribosome" "MHC protein binding" "chemokine receptor binding" ...
 $ GeneRatio  : chr  "21/1803" "45/1803" "18/1803" "23/1803" ...
 $ BgRatio    : chr  "49/18337" "180/18337" "40/18337" "69/18337" ...
 $ pvalue     : num  1.62e-09 2.90e-09 9.25e-09 8.13e-08 2.34e-07 ...
 $ p.adjust   : num  1.49e-06 1.49e-06 3.17e-06 2.09e-05 4.75e-05 ...
 $ qvalue     : num  1.35e-06 1.35e-06 2.87e-06 1.89e-05 4.30e-05 ...
 $ geneID     : chr  "XCL2/XCL1/CXCL16/CCL2/CCL7/CCL8/CCL13/CCL1/CCL5/CCL18/CCL3/CCL4/CCL3L3/PF4/PPBP/CXCL5/CXCL3/CXCL2/CXCL9/CXCL10/CXCL11" "RPS8/RPS27/RPLP2/MRPL49/RPS25/RPS29/RPL36AL/RPS27L/RPL4/MRPS11/RPS2/RPL23A/RPL23/RPS15/MRPL54/RPL36/RPS28/MRPL3"| __truncated__ "FCRL6/LAG3/CLEC7A/KLRD1/LILRB2/LILRB1/KIR2DS4/KIR3DL2/CD8A/CD8B/TUBB/TAP2/TAP1/TAPBP/TRGV9/TRGV3/PILRB/VCP" "XCL2/XCL1/CXCL16/CCL2/CCL7/CCL8/CCL13/CCL1/CCL5/CCL18/CCL3/CCL4/CCL3L3/CCR2/CCRL2/PF4/PPBP/CXCL5/CXCL3/CXCL2/CX"| __truncated__ ...
 $ Count      : int  21 45 18 23 13 54 8 9 19 29 ...
#...Citation
 T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu.
 clusterProfiler 4.0: A universal enrichment tool for interpreting omics data.
 The Innovation. 2021, 2(3):100141 

> enrich <-
+     enrichGO(
+         gene = genes,
+         OrgDb = org.Hs.eg.db,
+         keyType = 'SYMBOL',
+         ont = "MF",
+         pAdjustMethod = "BH",
+         pvalueCutoff  = 0.01,
+         qvalueCutoff  = 0.01, readable=TRUE)
Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]

**Comment by huerqiang** [comment]
Don't use `readable=TRUE` when `keyType = 'SYMBOL'`.

**Comment by huerqiang** [comment]
x@readable

**Comment by GuangchuangYu** [comment]
will be fixed in next release.
