### ISSUE TITLE
compareCluster working while using "fun = "enrichGO" but not "fun = "enrichPathway"" 

### ISSUE THREAD

**Issue by sarahalshammery** [YuLab-SMU/clusterProfiler#458]
Hello 

I've been using clusterProfiler for a while, and I've been having this issue for 3 days on multiple computers. compareCluster works great with fun = "enrichGO" / "enrichKEGG" but not "enrichPathway". Code below:
Example data and code from here: https://yulab-smu.top/biomedical-knowledge-mining-book/universal-api.html 

```
data(geneList,` package = "DOSE")
mydf <- data.frame(Entrez=names(geneList), FC=geneList)
mydf <- mydf[abs(mydf$FC) > 1,]
mydf$group <- "upregulated"
mydf$group[mydf$FC < 0] <- "downregulated"
mydf$othergroup <- "A"
mydf$othergroup[abs(mydf$FC) > 2] <- "B"
# this works ok
formula_res <- compareCluster(Entrez~group+othergroup, data=mydf, `fun="enrichKEGG")
#this gives an error
formula_reac <- compareCluster(Entrez~group+othergroup, data=mydf, `fun="enrichPathway")
Error in get(x, envir = ns, inherits = FALSE)    :
 object 'enrichPathway' not found

```
I have deleted R, and R studio and re installed. Have also made sure all of my packages are up to date as of 28/04/2022. 

Would appreciate any help with this - Thank you.

**Comment by GuangchuangYu** [comment]
You need to have `ReactomePA` installed and `library(ReactomePA)` to load the package before you can use `enrichPathway()`.

**Comment by sarahalshammery** [comment]
Thanks @GuangchuangYu , I have done that.

**Comment by GuangchuangYu** [comment]
just pass `enrichPathway` without quoting.

**Comment by GuangchuangYu** [comment]
@huerqiang fixed it <https://github.com/YuLab-SMU/clusterProfiler/blob/master/R/compareCluster.R#L61>.
