### ISSUE TITLE
problem in KEGG paths download

### ISSUE THREAD

**Issue by tester-0102** [YuLab-SMU/clusterProfiler#472]
https://github.com/YuLab-SMU/clusterProfiler/issues/218
i have exactly the same problem, i cant solve it
RStudio 2022.02.3+492 "Prairie Trillium" Release for Windows
R 4.2.0
i have installed clusterprofiler
error message:
Reading KEGG annotation online:
fail to download KEGG data...
Error in download.KEGG.Path(species) :
Failed to download KEGG data. Wrong 'species' or the network is unreachable. The 'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html

test code:
results1 <- enrichKEGG(gene = gene, organism = 'hsa', pvalueCutoff = 0.05)

any help; is there any compatibility problem with r or rstudio versions;
thanx

**Comment by zhangyz1997** [comment]
Just refer to my issue #470 if you are a Windows user.
`options(clusterProfiler.download.method = "wininet")`
Or wait for an upgrade.

**Comment by tester-0102** [comment]
great!!thanks a lot, problem solved!

**Comment by tester-0102** [comment]
another problem with KEGG paths now, has to do with clusterprofile?
code:
frame = toTable(org.Hs.egPATH) #ok
keggframeData = data.frame(frame$path_id, frame$gene_id) #ok
head(keggframeData) #ok
keggFrame=KEGGFrame(keggframeData,organism="Homo sapiens")

and on 4th line i got the error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer


is network problem or KEGG parameters?
than again...

**Comment by GuangchuangYu** [comment]
fixed in <https://github.com/YuLab-SMU/clusterProfiler/pull/471>.

**Comment by Beta-BuTX** [comment]
> Just refer to my issue #470 if you are a Windows user. `options(clusterProfiler.download.method = "wininet")` Or wait for an upgrade.

Thank you so much, it helps me too!
