### ISSUE TITLE
merge_result error

### ISSUE THREAD

**Issue by wbvguo** [YuLab-SMU/clusterProfiler#473]
I run into an error when using the merge_result function:
`merge_result(list(A= ego_A, B= ego_A))`

Here the `ego_A` is the enrichResult class object generated by enrichGO function. The test example can be found [here](https://github.com/wbvguo/test/blob/main/pkg_data/ego_A.rds)

Error message:
`Error in if (fun == "enrichDO" || fun == "enrichNCG") { : missing value where TRUE/FALSE needed`

SessionInfo:
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS
DOSE_3.18.3            
enrichplot_1.12.3     
clusterProfiler_4.0.5
org.Mm.eg.db_3.13.0
```

This error is also found (but unsolved) in a previous [post](https://github.com/YuLab-SMU/clusterProfiler/issues/411). Do you have any advice on how to solve the issue?

**Comment by GuangchuangYu** [comment]
![image](https://user-images.githubusercontent.com/626539/173817371-1da1df67-9b5e-4377-836c-0790460121f4.png)

the file you provided is corrupt

**Comment by wbvguo** [comment]
Thank you for the quick reply, please use the following command to load the RDS file

```
egoA = readRDS("path_to_the_rds")
```

I have tested it with the file on the github, it should be fine

**Comment by GuangchuangYu** [comment]
fixed in github version.

![image](https://user-images.githubusercontent.com/626539/174698716-97a023f3-e411-4a74-adc1-e52d43b54793.png)
