### ISSUE TITLE
gseKEGG always get stuck

### ISSUE THREAD

**Issue by alienzj** [YuLab-SMU/clusterProfiler#474]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and followed the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure you are using the latest release version
	* [x] read the [documentation](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe your issue

When run gseKEGG, it alwas get stuck.

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what you expected and what actually happened)

### Ask in the right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with the tag `clusterProfiler`

**Comment by alienzj** [comment]
When set `use_internal_data = TRUE`,
```
gseaKEGG_all_bnt <- gseKEGG(
    geneList = foldchanges_all_bnt,
    # ordered named vector of fold changes (Entrez IDs are the associated names)
    organism = "hsa", # supported organisms listed below
    nPerm = 1000, # default number permutations
    minGSSize = 20, # minimum gene set size (# genes in set) - change to test more sets or recover sets with fewer # genes
    pvalueCutoff = 0.05, # padj cutoff value
    use_internal_data = TRUE,
    seed = TRUE,
    verbose = TRUE)
```

Error:
```
R[write to console]: Failed with error:  
R[write to console]: 
R[write to console]: 'there is no package called 'KEGG.db''
R[write to console]: 
R[write to console]: 

R[write to console]: In addition: 
R[write to console]: Warning message:

R[write to console]: Ensembl will soon enforce the use of https.
Ensure the 'host' argument includes "https://" 

R[write to console]: Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'as.list': there is no package called 'KEGG.db'
```

**Comment by GuangchuangYu** [comment]
The KEGG.db was removed from Bioconductor, and this parameter won't work.

**Comment by GuangchuangYu** [comment]
please upgrade to the latest release version of clusterProfiler. see also <https://github.com/YuLab-SMU/clusterProfiler/issues/256#issuecomment-1156644818>.

**Comment by alienzj** [comment]
Thanks ! I will try the latest version of clusterProfiler.
