### ISSUE TITLE
Error with enrichKEGG

### ISSUE THREAD

**Issue by jms-93** [YuLab-SMU/clusterProfiler#480]
Hello, I am trying to create a KEGG annotation using the following code:

```{r} 
search_kegg_organism('human', by='common_name') 
sigGenes.o_vs_m <- dds.results %>%
  drop_na(Entrez, FDR) %>%
  filter(FDR < 0.1 & abs(logFC) > 0.58) %>%
  pull(Entrez)
kk <- enrichKEGG(gene = dds.results, organism = 'hsa')
```

This previously worked, but now I'm getting the following error:

> kk <- enrichKEGG(gene = sigGenes.o_vs_m, organism = 'hsa')
Reading KEGG annotation online:
Warning in utils::download.file(url, quiet = TRUE, method = method, ...) :
  URL 'https://rest.kegg.jp/link/hsa/pathway': status was 'Failure when receiving data from the peer'
fail to download KEGG data...
Error in download.KEGG.Path(species) : 
  'species' should be one of organisms listed in 'http://www.genome.jp/kegg/catalog/org_list.html'...

The species is indeed the one listed in http://www.genome.jp/kegg/catalog/org_list.html (hsa) so that is not wrong, so it seems to be a problem with connecting to KEGG. 

Restarting RStudio, my PC and trying the next day did not work. 
There are no problems with my network connection, and all packages are up to date.

Anyone else have this issue / know how to fix it?

**Comment by xcliu-oc** [comment]
i have the same issue. please advice.

**Comment by GuangchuangYu** [comment]
see https://github.com/YuLab-SMU/clusterProfiler/issues/256

**Comment by xcliu-oc** [comment]
should be #471
