### ISSUE TITLE
fail to download KEGG data...

### ISSUE THREAD

**Issue by htqqdd** [YuLab-SMU/clusterProfiler#481]
fail to download KEGG data...
Error in `colnames<-`(`*tmp*`, value = c("path_id", "path_name")) : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In utils::download.file(url, quiet = quiet, method = "libcurl",  :
  URL 'https://rest.kegg.jp/list/pathway': status was 'Failure when receiving data from the peer'

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/clusterProfiler/issues/256> and update to the latest release version.
