### ISSUE TITLE
Understanding reproducibility fixing by setting seed

### ISSUE THREAD

**Issue by L3ft2di3** [YuLab-SMU/clusterProfiler#519]
Hey,

I learned that GSEA analysis results are not reproducible when seed = FALSE is true. I was struggling quite a while until I noticed the seed option for GSEA functions. To which extend are the results of a GSEA seed dependent? I mean, at which state of the analysis are random numbers used? My understanding of a GSEA was that it's solely dependent on fold change.
Could you maybe elaborate a bit on this? Thank you!
Cheers
Thorben

**Comment by guidohooiveld** [comment]
Under the hood, `clusterProfiler` uses the (fast) GSEA algorithm implemented in the package` fgsea`. Specifically, the function `fgseaMultilevel()` is used, which is initially tuned by `fgseaSimple()`. `fgseaSimple()` uses gene sampling to estimating the empirical P-values. Gene sampling is random, except when a `seed` is set.

For more info on this see e.g. the `fgsea` preprint [here](estimating the empirical P-values.) (page 7, line 159), and the thread on the `fgsea` GitHub here: https://github.com/ctlab/fgsea/issues/120.

**Comment by L3ft2di3** [comment]
Thank you for the explanation and the additional info. Will close the threat.
