### ISSUE TITLE
DEGs list for compareCluster generation

### ISSUE THREAD

**Issue by whiteorchid** [YuLab-SMU/clusterProfiler#524]
Dear authors,

Thanks for the great tool!

May I have your guidance that how to generate the DEGs list? The paper shows the GSE8057 as an example, so does the _DEGs list for 0h, 2h, 6h, 24h_ come from `**0h vs pre; 2h vs pre; 6h vs pre; 24h vs pre**`? If do not have pre(before treatment), does that means can only see the results 2h, 6h, 24h?

Thank you very much! Best!

**Comment by huerqiang** [comment]
You need the DEGs of '0h vs pre; 2h vs pre; 6h vs pre; 24h vs pre'.
