### ISSUE TITLE
EnrichWP - 'wininet' method is deprecated

### ISSUE THREAD

**Issue by SLMaas** [YuLab-SMU/clusterProfiler#529]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and followed the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure you are using the latest release version
	* [x] read the [documentation](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe your issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what you expected and what actually happened)

### Ask in the right place

* [x] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with the tag `clusterProfiler`

**Comment by SLMaas** [comment]
Dear all, 

I wanted to perform a ORA analysis for WikiPathways. I did this in the past often. I run my previous used (and working code):
wp <- enrichWP(ids$ENTREZID, organism = "Homo sapiens") 

However, I get the following output: 
> wp <- enrichWP(ids$ENTREZID, organism = "Homo sapiens") 
Warning: the 'wininet' method is deprecated for http:// and https:// URLs--> No gene can be mapped....
--> Expected input gene ID: 
--> return NULL...

Also when I run, I get the following results: 
> get_wp_organisms()
character(0)

I updated remotes, R and R studio, but nothing works. Someone has an idea how I can continue and get my ORA analysis for WikiPathways. 

Thanks in advance!
Sanne

**Comment by yuanlizhanshi** [comment]
Hello. I recently noticed this problem.

I check the source code of the clusterProfiler and found that the [link](https://data.wikipathways.org/current/gmt/) in function **get_wp_data** failed. 

Which should update with the new link:https://wikipathways-data.wmcloud.org/20221210/gmt/

Below is my solution for solving this problem:

Download your species gmt file in the above [link](https://wikipathways-data.wmcloud.org/20221210/gmt/)

then load with function **read.gmt.wp** in clusterProfiler:

`
wiki_pathway <- read.gmt.wp('wikipathways-20221210-gmt-Mus_musculus.gmt.txt')
`
add the function:

```
enrichWP2 <- function (gene, wiki_gmt,...) 
{
  prepare_WP_data <- function (wp2gene) 
  {
    wpid2gene <- wp2gene %>% dplyr::select(.data$wpid, .data$gene)
    wpid2name <- wp2gene %>% dplyr::select(.data$wpid, .data$name)
    list(WPID2GENE = wpid2gene, WPID2NAME = wpid2name)
  }
  
  wpdata <- prepare_WP_data(wiki_gmt)
  res <- enricher(gene, TERM2GENE = wpdata$WPID2GENE, TERM2NAME = wpdata$WPID2NAME, 
                  ...)
  if (is.null(res)) 
    return(res)
  return(res)
}
```

```
gseWP2 <- function (geneList, wiki_gmt, ...) 
{
  prepare_WP_data <- function (wp2gene) 
  {
    wpid2gene <- wp2gene %>% dplyr::select(.data$wpid, .data$gene)
    wpid2name <- wp2gene %>% dplyr::select(.data$wpid, .data$name)
    list(WPID2GENE = wpid2gene, WPID2NAME = wpid2name)
  }
  
  wpdata <- prepare_WP_data(wiki_gmt)
  res <- GSEA(geneList, TERM2GENE = wpdata$WPID2GENE, TERM2NAME = wpdata$WPID2NAME, 
              ...)
  if (is.null(res)) 
    return(res)
  return(res)
}
```

Then, use the new function to replace the old function and you will get the enrichment results.

such as:
`enrichWP_res <- enrichWP2(names(gsea_genelist),wiki_pathway,pvalueCutoff = 0.1)`
`gsea_wiki <- gseWP2(gsea_genelist,wiki_pathway, pvalueCutoff = 0.1)`

**Comment by SLMaas** [comment]
Thanks a lot! This solved the problem :)
