### ISSUE TITLE
download_KEGG produces no obs for KEGGPATHID2EXTID

### ISSUE THREAD

**Issue by amnotagoldfish** [YuLab-SMU/clusterProfiler#539]
This issue occured today, despite using this code for the last two or so weeks. 

When running:

download_KEGG(species = "sasa", keggType = "KEGG", keyType = "kegg")  -> v

The resulting list contains two dfs, the desired complete KEGGPATHID2NAME, but no observations for KEGGPATHID2EXTID.
Running this code previously, i.e. before 14:00 GMT, provided a df with observations used for further analysis, but not anymore, without any apparent changes in the package, R version, or error messages in R. 

Further, attempting to map using enrichKEGG returns the following message:
"--> No gene can be mapped....
--> Expected input gene ID: 
--> return NULL..."

dummy code: 
genes <- c("100135779", "100136349", "100136351", "100136352", "100136353", "100136354", "100136355", "100136356", "100136357", "100136358", "100136359", "100136360", "100136364", "100136365", "100136366", "100136367", "100136369", "100136371", "100136372", "100136373")
#actual sasa genes

enrichKEGG(genes, organism = "sasa", keyType = "kegg", pvalueCutoff = 0.05)

This again had no issue prior to 14:00

**Comment by maxfieldk** [comment]
Hi,
I am having this exact same issue but with rabbit ("ocu") as my organism.
The code produced proper output three hours ago, and now when rerunning it I get the:
"--> No gene can be mapped....
--> Expected input gene ID:
--> return NULL..."
I also get an empty KEGGPATHID2EXTID df and one complete KEGGPATHID2NAME df when calling download_KEGG.
Very strange behavior..

**Comment by XeriusLab** [comment]
Hi,
I get the same error using  enrichKEGG( ..., organism = "mmu" ) when using it with mouse entrez IDs.  "hsa" with human gene entrez ids works fine. The exact same code and datasets were run the day before (26/02) without any issue but stopped working on the 27th in the afternoon CET.

**Comment by amnotagoldfish** [comment]
> 
Hi 

As of now I am looking into combining getGeneKEGGLinks and getKEGGPathwayNames from the package limma for my organism, "sasa", with the same functions for KEGGs "ko", although it probably will require some additional, potentially cumbersome, calculations to get similar output.

**Comment by maxfieldk** [comment]
Hey,
Can confirm I'm still having this issue today. Only enough - both yesterday and today the "enrichMKEGG" returns proper output for the rabbit. I will attempt your limma workaround amnotagoldfish, thanks for the tip!

**Comment by trnguyenuka** [comment]
Hello, 

I guess I'm facing a similar issue here, I'm not downloading any KEGG data, but I keep getting the error 
"--> No gene can be mapped....
--> Expected input gene ID:
--> return NULL..."

It's weird because the code run just fine this morning ...

**Comment by maxfieldk** [comment]
Here is a workaround I got working. 
Basically I download and wrangle the missing set of annotations for use with the enricher and GSEA functions in cluster profiler.
Note that my species of interest (rabbit) has kegg code "ocu".
Hope this helps!
```
#### KEGG
library(KEGGREST)
kocu <- keggLink("pathway", "ocu")
genes <- names(kocu)
pathways <- unname(kocu)
term2gene <- data.frame(term = pathways, gene = genes)
term2gene <- term2gene %>%
    mutate(term = str_sub(term, start = 9)) %>%
    mutate(gene = str_sub(gene, start = 5))

v <- download_KEGG(species = "ocu", keggType = "KEGG", keyType = "kegg")
term2name <- v[["KEGGPATHID2NAME"]]
term2name <- term2name %>%
    rename(term = from, name = to) %>%
    mutate(term = str_sub(term, start = 4))
# GSEA
res <- res[order(-res$stat), ] %>% drop_na()
ordered_gene_list <- res$stat
eg <- bitr(res$gene, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = rabbit)
names(ordered_gene_list) <- eg$ENTREZID
gse <- GSEA(geneList = ordered_gene_list, TERM2GENE = term2gene, TERM2NAME = term2name)
```

**Comment by cherrie-g** [comment]
I have met the same issue. And I have just run successfully at 2.28 10:00AM (GMT+08:00). When will this fixed?
