### ISSUE TITLE
Fetching the gene sets for non-human (at least mouse and pig) fails for KEGG

### ISSUE THREAD

**Issue by GeertvanGeest** [YuLab-SMU/clusterProfiler#541]
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and followed the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)? 
*Note that the [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback)  link is dead. *
	* [x] make sure you are using the latest release version
	* [x] read the [documentation](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe your issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [x] your code should contain comments to describe the problem (*e.g.* what you expected and what actually happened)

When I try to run the following:

```r
clusterProfiler::gseKEGG(geneList = c('14469' = 3, '229898' = 2), organism = 'mmu', keyType = 'ncbi-geneid')
```

It returns:

```r
Reading KEGG annotation online: "https://rest.kegg.jp/link/mmu/pathway"...
Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway"...
Reading KEGG annotation online: "https://rest.kegg.jp/conv/ncbi-geneid/mmu"...
preparing geneSet collections...
--> Expected input gene ID: 
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....
```

14469 and 229898 are mouse genes. 

But it works for human. It seems that the gene sets are not fetched. This works:

```r
species <- 'hsa'
KEGG_DATA <- clusterProfiler:::prepare_KEGG(species, "KEGG", 'kegg')
geneSets <- DOSE:::getGeneSet(KEGG_DATA)
geneSets
```

But this returns an empty list (`named list()`):

```r
species <- 'mmu'
KEGG_DATA <- clusterProfiler:::prepare_KEGG(species, "KEGG", 'kegg')
geneSets <- DOSE:::getGeneSet(KEGG_DATA)
geneSets
```

### Ask in the right place

* [x] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with the tag `clusterProfiler`

**Comment by SodzieR** [comment]
Same for me. My old .Rmd scripts suddenly stopped generating the GSEA results for KEGG pathway enrichment. I have been using ENTREZIDs from org.Mm.eg.db::org.Mm.eg.db to this date but suddenly it stopped working with error:

`> set.seed(the_seed)
> kegg_gsea_dge_out <- gseKEGG(
+   geneList     = geneList_dge_no_dups,
+   organism     = 'mmu',
+   minGSSize    = 15,
+   maxGSSize    = 500,
+   pvalueCutoff = 1,
+   verbose      = TRUE,
+   seed         = TRUE
+ )
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....`

My data:

`> head(geneList_dge_no_dups)
   404743    435286 100503388    670496      <NA>     71386 
 21.48182  19.96099  19.94172  18.42383  17.61011  16.42252`

**Comment by GeertvanGeest** [comment]
It seems to be an issue on the side of KEGG:

```r
keggpathid2name.df <- read.delim(url('https://rest.kegg.jp/list/pathway'), header = FALSE)
spc <- substr(keggpathid2name.df$V1, 1, 3)
table(spc)
```

Returns:

```
ath ccr cel dme hsa map sce xla 
  5   1   2   8 229 310   5   2 
```

So apparently mainly the human pathways are left?

**Comment by SodzieR** [comment]
Could this be related to this commit: https://github.com/YuLab-SMU/clusterProfiler/commit/fa231bd100e5d0fb3aa37639df3a227863403de9

Not sure if updating the package will help but I will try nonetheless.

**Comment by GeertvanGeest** [comment]
I guess it's announced here: https://www.kegg.jp/kegg/rest/

> Announcement: Minor update of KEGG API

> Starting on March 1, 2023 the list operation of KEGG API returns KEGG identifiers without the database name in most cases, in compatible with the form shown in Figure 1 of the recent [NAR article](https://doi.org/10.1093/nar/gkac963).

I suppose if the organism name of a pathway is changed to 'map' (e.g. `mmu00010` to `map00010`) it's solved.

**Comment by GeertvanGeest** [comment]
> Could this be related to this commit: [fa231bd](https://github.com/YuLab-SMU/clusterProfiler/commit/fa231bd100e5d0fb3aa37639df3a227863403de9)
> 
> Not sure if updating the package will help but I will try nonetheless.

A yes, probably solved.

**Comment by GeertvanGeest** [comment]
Was also an issue here: https://github.com/YuLab-SMU/clusterProfiler/issues/539
