### ISSUE TITLE
bitr_kegg malfunction 

### ISSUE THREAD

**Issue by Ruiqi-CUB** [YuLab-SMU/clusterProfiler#544]
Hi Prof. Yu! I was trying to mapping K number (KEGG Orthology number) to ko (KEGG pathways) with `bitr_kegg` fuction. I found that  some K numbers can't be mapped to ko even it does have corresponding pathways on KEGG. 

For example:
```
y <- bitr_kegg("K14704", "kegg", "Path", "ko")
Warning message:
In bitr_kegg("K14704", "kegg", "Path", "ko") :
  100% of input gene IDs are fail to map...
```

On [KEGG website](https://www.genome.jp/dbget-bin/www_bget?ko:K14704), it does have two corresponding pathways: 

map04978 Mineral absorption
map05208 Chemical carcinogenesis - reactive oxygen species

Further, I used a large set of K numbers from the emapper annotation of my transcriptome data, one third was not able to mapped to ko pathways. I do understand that some K numbers are not corresponding to any pathways, but upon manully checking (as above), that probably not the case. Could you please help me with it? Thanks a lot!

```
> str(KOs)
 chr [1:4277] "K02727" "K17277" ...

x <- bitr_kegg(KOs, "kegg", "Path", "ko")
Warning message:
In bitr_kegg(KOs, "kegg", "Path", "ko") :
  66.99% of input gene IDs are fail to map...

> str(x)
'data.frame':	3404 obs. of  2 variables:
 $ kegg: chr  "K00121" "K00128" "K00129" "K00134" ...
 $ Path: chr  "map00010" "map00010" "map00010" "map00010" ...
```

**Comment by guidohooiveld** [comment]
Maybe you experienced a temporarily glitch, since it seems to work now:


```
> library(clusterProfiler)
> bitr_kegg("K14704", "kegg", "Path", "ko")
Reading KEGG annotation online: "https://rest.kegg.jp/link/ko/pathway"...
Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway/ko"...
    kegg    Path
1 K14704 ko04978
2 K14704 ko05208
Warning messages:
1: In utils::download.file(url, quiet = TRUE, method = method, ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
2: In utils::download.file(url, quiet = TRUE, method = method, ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
>
> packageVersion("clusterProfiler")
[1] ‘4.6.1’
> 
```

**Comment by guidohooiveld** [comment]
Also, the fact that you loose some of your KO ids may also be expected; whether one-third is much is difficult to judge.

As example, when using the 2 KO ids that were visible in your input ("K02727" and "K17277").

```
> ids <- c("K02727", "K17277")
> KOs <- c("K02727", "K17277")
> bitr_kegg(KOs, "kegg", "Path", "ko")
    kegg    Path
1 K02727 ko03050
2 K02727 ko05010
3 K02727 ko05012
4 K02727 ko05014
5 K02727 ko05016
6 K02727 ko05017
7 K02727 ko05020
8 K02727 ko05022
Warning message:
In bitr_kegg(KOs, "kegg", "Path", "ko") :
  50% of input gene IDs are fail to map...
>

```
These results show that K02727 can be mapped to multiple (=8) pathways, but K17277 does not.

If you then check these 2 entries on KEGG website (https://www.genome.jp/kegg/ko.html):
K02727 has symbol PSMA3. and is indeed mapped to 8 **pathways**: https://www.genome.jp/entry/K02727

in contrast, 
K17277 has symbol EPS8, and is only mapped to 3 **diseases** (and no pathways!): https://www.genome.jp/entry/K17277

So the output you got ("which pathways are associated with my list of KEGG orthology ids") corresponds perfectly with what KEGG itself also provides.

**Comment by Ruiqi-CUB** [comment]
Thanks a lot! 
I think it is a `clusterProfiler` version issue. I was using v4.6.0. I updated it to v4.6.1, reopened Rstudio, probelm solved!
