### ISSUE TITLE
[not working] Enrichment analysis based on kegg for zebrafish

### ISSUE THREAD

**Issue by paolabc** [YuLab-SMU/clusterProfiler#546]
Hello There!

I am doing the enrichment analysis based on kegg. The analysis is based on zebrafish entrezid/ncbi-geneid

Clusterprofiler seems to work for this example
```
data(geneList, package='DOSE')
de <- names(geneList)[1:100]
yy <- enrichKEGG(de, pvalueCutoff=0.01)
head(yy)

```

But when I tried my code, it does not work. I did it for my whole dataframe and then I tried also to do it a small vector.
Here is the code that I treid with this small vector
```
gene<-c("108179356","562008","101886804","100007552","110437771","561067","108182459","100331916","101885332","564515",
          "103910768","641469","100149422","101887060","100332327","110440209","101884367","100321135","101884831","110438346","100330864","568416","791732","100333496","103910561","100033600","100535845","564958","101885505","100003496",
          "101886822","561322","100150906","110437767","100537716","101883600","100534958","100334351","100334396","110439967","108180085","100126129","103910381","751636","558010","402956","110438542","445250","140426","103909751",
          "101883443","606720","101885018","767650","794549","100333562","100329648","101883749","30491","565074",
          "572000","541341","101886406","569265","110439426","100536937","568476","101885577","393642","100073325",
          "334527","569700","100126810","108179091","103910871","563246","553303","767727","321786","100101643",
          "100331412","406525","393877","100124605","404607","100142642","571832","101884972","560315","110437923",
       "100006428","100333322","797319","100534706","101886995","403048","558563","100334085","110439304","110438375",
          "541495","100001581","751644","799405","550161","101886862","100536995","100322009","493600","570947",
          "792293","101883651","101887154","100150732","108191751","100003113","798168","322609","555340","325226",
          "449647","323922","100535070","100149562","100334245","100320750","568060","555985","336124","569908",
          "796658","564701","100151323","100332814","103911451","555875","402973","559162","100333484","570258",
          "564395","557566","567867","100535820","368924","572146","110439111","100330358","100333826","100329818",
          "386638","108180146","100333352","792676","751624","334459","110439911","393606","100332028","572463",
          "557996","327143","100334248", "561095","553318","561893","554013","556081","563670","192312", 
          "795788","64608", "562208","555764","567288","100000570", "100037374", "555703","100333916", "436710", 
          "768186","406756","559809","559447","386801","558800","100538153", "323926","334474","338317", 
          "554016","436734","393260","170455","406416","792610","436793","101886789", "563011","767805", 
          "553505","553371","569489","30715", "565037","323679","606585","562742","553243","553451", 
          "559643","100034609", "557451","571383","100002795" ,"100000256" ,"796163","793727","100334879" ,"325402", 
          "566102","555285","798791","100535772" ,"566728","100033647", "559928","110438638" ,"563017","393777", 
          "560549","108191970" ,"266799","100332164","360150","407708","100000165", "334561","100007362", "572187", 
          "565952","550239","559976","550436","563876","565434","562999","793823","562076","336984", 
          "567731","100332125" ,"404211","445133","566695","559457","560418","445026","101882648", "492364", 
          "560639","561921","323181","406519","81590", "415203","794108","791150","566146","571441")
mf <- enrichKEGG(gene, organism = "dre",keyType = 'ncbi-geneid')
```
The message that I received for this result and also for my whole dataset.
--> No gene can be mapped....
--> Expected input gene ID: 
--> return NULL.

What could be the reason for it? 

Besides, I am sure also that my entrezids in my whole dataset are character objects and they are not considered as numbers. Since entrezid are only numbers, it could be interepreted in this way.

Thank you in advance for taking this time

**Comment by yangxinzhi** [comment]
I ran into the same problem when I used the same data with this package and kobas analysis and got completely different results. Yesterday it was shown that no genes were able to map, today it is shown that no single pathway is significant. I checked my id number carefully and there is no problem.
![image](https://user-images.githubusercontent.com/125720871/222618083-f391b31b-d512-44db-822d-e08f5465747a.png)
![image](https://user-images.githubusercontent.com/125720871/222618137-6a0d26fd-8352-4f52-a112-d068636ba04b.png)

**Comment by paolabc** [comment]
Hello There!

I also tried some minutes ago Kobas analysis, and it worked there. I do not know why  erros and no analysis are happening on ClusterProfiler analysis. 

By the way, I also searched for some answers. I found this poster from some years ago ( link : https://www.biostars.org/p/305258/#9556298) . The wangchangliang0209's answer was that it is possible that for other animal, diregard humans, it need another input. So far, I tried "dre_102725537,dre_795613,dre_393541,dre_100000710,dre_325037,dre_558156" and "DRE_102725537,DRE_795613,DRE_393541,DRE_100000710,DRE_325037,DRE_558156". Both did not work  for me.

**Comment by yangxinzhi** [comment]
So we should  use enrichMKEGG  ?

**Comment by huerqiang** [comment]
Already soved by the Github version of clusterProfiler.

**Comment by guidohooiveld** [comment]
.... and install the Github version for example through:

`remotes::install_github("YuLab-SMU/clusterProfiler")`.

Current Github version is v4.7.1.

**Comment by paolabc** [comment]
Thank you all for your support.! The installation  from GitHub solved my issue.
