### ISSUE TITLE
gseKEGG  no  gene  can be mapped 

### ISSUE THREAD

**Issue by Feifei0511** [YuLab-SMU/clusterProfiler#550]
在此之前我用同样的代码跑过一次没有出现报错，但跑第二次的时候出现这样的报错，一直得不到解决，请问我这个应该怎么修改呢？
> KEGG <- gseKEGG(gene_fc,use_internal_data = F,organism = "hsa",pvalueCutoff = 0.05)
preparing geneSet collections...
--> Expected input gene ID: 
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped....

**Comment by ZZhenQi** [comment]
> 在此之前我用同样的代码跑过一次没有出现报错，但跑第二次的时候出现这样的报错，一直得不到解决，请问我这个应该怎么修改呢？
> 
> > KEGG <- gseKEGG(gene_fc,use_internal_data = F,organism = "hsa",pvalueCutoff = 0.05)
> > preparing geneSet collections...
> > --> Expected input gene ID:
> > Error in check_gene_id(geneList, geneSets) :
> > --> No gene can be mapped....

更新最新的Clusterprofiler包

**Comment by liuchanlon** [comment]
I have a similar issue. The code running 4 months ago worked very well. But now showing like --> Expected input gene ID: 
Error in check_gene_id(geneList, geneSets) : --> No gene can be mapped....

**Comment by huerqiang** [comment]
@liuchanlon Please ue the latest version of clusterProfiler.

**Comment by liuchanlon** [comment]
I have updated the lastest version of clusterProfiler

**Comment by liuchanlon** [comment]
it does not work

**Comment by liuchanlon** [comment]
> library(clusterProfiler)

clusterProfiler v4.4.4  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use clusterProfiler in published research, please cite:
T Wu, E Hu, S Xu, M Chen, P Guo, Z Dai, T Feng, L Zhou, W Tang, L Zhan, X Fu, S Liu, X Bo, and G Yu. clusterProfiler 4.0: A universal enrichment tool for interpreting omics data. The Innovation. 2021, 2(3):100141

Attaching package: ‘clusterProfiler’

The following object is masked from ‘package:stats’:

    filter

**Comment by huerqiang** [comment]
If you want to install the lastest version of clusterProfiler by :` BiocManager::install("clusterProfiler")`, using the release version of Bioconductor is necessory. I strongly  recommend that you install the latest version of R (V 4.2.3) and reinstall clusterProfiler and DOSE.

**Comment by XB2965** [comment]
I also have the similar issue. R version 4.3.2 (2023-10-31 ucrt); Bioconductor version 3.18 (BiocManager 1.30.22); clusterProfiler version: 4.10.0; KEGGREST version: 1.42.0. That is to say all the software and R packages are the latest. organism = "sce". It still shows that "preparing geneSet collections...
--> Expected input gene ID: YLR446W,YAL054C,YGR244C,YHR183W,YJL045W,YPL231W
Error in check_gene_id(geneList, geneSets) : 
  --> No gene can be mapped...."   This error still exits even though I have tried many many times. So what should I do to solve this problem?
