### ISSUE TITLE
制作KEGG富集分析本地文件，结果描述为NA

### ISSUE THREAD

**Issue by ZZhenQi** [YuLab-SMU/clusterProfiler#551]
使用Y叔的代码进行制作本地KEGG.db文件后，测试发现Description部分内容为NA，请问各位大神如何解决？

remotes::install_github("YuLab-SMU/createKEGGdb",force = T)
library(createKEGGdb)
species <-c("hsa","mmu","rno")
create_kegg_db(species)
install.packages("./KEGG.db_1.0.tar.gz", repos=NULL,type="source")
library(KEGG.db)
library(clusterProfiler)

data(geneList, package="DOSE")
gene <- names(geneList)[abs(geneList) > 2]
kk <- enrichKEGG(gene         = gene,
                 organism     = 'hsa',
                 pvalueCutoff = 0.05,
                 qvalueCutoff = 0.05,
                 use_internal_data =T)
nrow(kk)
head(kk)

<img width="778" alt="image" src="https://user-images.githubusercontent.com/115803239/222943675-90436813-6d31-4ec2-9115-38db5177e684.png">

**Comment by dongqing7** [comment]
我也遇到了同样的问题

**Comment by huerqiang** [comment]
@dongqing7 安装Github版本的createKEGGdb可解决此问题。如果还遇到问题，请将clusterProfiler和DOSE也一起更新。

**Comment by xiangrong7** [comment]
还是不行

**Comment by Zhangmochen-zmc** [comment]
按照您的方法全部更新后，仍然存在这个问题

**Comment by JiahaoWongg** [comment]
anyone help?

**Comment by huerqiang** [comment]
Please make sure you are using the latest version of `createKEGGdb`, `clusterProfiler` and `DOSE`. If the issue persists, please output your sessionInfo() results and I will take a closer look at what the problem is.

**Comment by JiahaoWongg** [comment]
@JiahaoWongg I help you. This is the second time I encountered this problem. This time I found that there is a path ID number in `kk`, so we can match the corresponding `Description`. The following simple code can solve this problem:

```R
kk <- enrichKEGG(gene= gene,organism= 'hsa',pvalueCutoff = 0.05,qvalueCutoff = 0.05,use_internal_data = TRUE)
head(kk@result$Description)
# [1] NA NA NA NA NA NA
all_path = as.data.frame(KEGG.db::KEGGPATHID2NAME)
kk@result$Description = all_path$path_name[match(kk@result$ID, all_path$path_id)]
head(kk@result$Description)
# [1] "Cell cycle"
# [2] "Oocyte meiosis"
# [3] "Cellular senescence"
# [4] "Viral protein interaction with cytokine and cytokine receptor"
# [5] "PPAR signaling pathway"
# [6] "Motor proteins"
```

same with `use_internal_data = FALSE`:

```R
kk <- enrichKEGG(gene= gene,organism= 'hsa',pvalueCutoff = 0.05,qvalueCutoff = 0.05,use_internal_data = FALSE)
head(kk@result$Description)
# [1] "Cell cycle"
# [2] "Oocyte meiosis"
# [3] "Cellular senescence"
# [4] "Viral protein interaction with cytokine and cytokine receptor"
# [5] "PPAR signaling pathway"
# [6] "Motor proteins"
```
