### ISSUE TITLE
wikipathways link has changed ! new one : https://wikipathways-data.wmcloud.org/current/gmt/

### ISSUE THREAD

**Issue by BelHassiba** [YuLab-SMU/clusterProfiler#559]
The wikipathways previous link (https://data.wikipathways.org/current/gmt/)  is not available anymore. 
Must be change into https://wikipathways-data.wmcloud.org/current/gmt/ in  wikiPathways.R.

To fix the problem locally and quickly:

    1. download clusterProfiler from git : 
    git clone https://github.com/YuLab-SMU/clusterProfiler
    2. Go to clusterProfiler/R/wikiPathways.R and change https://data.wikipathways.org/current/gmt/ by the new link https://wikipathways-data.wmcloud.org/current/gmt/. Save changes of corse
    3. install the package : 
    devtools::install("/path/to/local/clusterProfiler/")

**Comment by WillieYu** [comment]
I tested the fix and I can confirm it works.

**Comment by AlexanderPico** [comment]
This "fix" appears to have been reverted already, which is good. Just for completeness, I'll confirm the correct URL for accessing WikiPathways GMT files is https://data.wikipathways.org/current/gmt/. This uses the forward-compatible domain (data.wikipathways.org) which may redirect to alternative hosts in the future as infrastructure changes. The wmcloud URL, by contrast, was used for a many years, but is now a dead link.
