### ISSUE TITLE
KEGG error:BiocParallel errors

### ISSUE THREAD

**Issue by Feifei0511** [YuLab-SMU/clusterProfiler#568]
when I run the code, it shows the error,but I don't know how to solve it

> KEGG <- gseKEGG(gene_fc,use_internal_data = F,organism = "hsa")
preparing geneSet collections...
GSEA analysis...
Error: BiocParallel errors
  13 remote errors, element index: 1, 7, 13, 19, 25, 31, ...
  61 unevaluated and other errors
  first remote error:
Error in fgseaMultilevelCpp(x[, ES], stats, unique(x[, size]), sampleSize, : could not find function "fgseaMultilevelCpp"
In addition: There were 15 warnings (use warnings() to see them)

**Comment by huerqiang** [comment]
You should update your fgsea package. If it still report errors, please provide your seeioninfo.
