### ISSUE TITLE
KEGG ：No gene can be mapped....

### ISSUE THREAD

**Issue by linianbin211** [YuLab-SMU/clusterProfiler#569]
### Prerequisites
platform       x86_64-w64-mingw32               
arch           x86_64                           
os             mingw32                          
crt            ucrt                             
system         x86_64, mingw32                  
status                                          
major          4                                
minor          2.1                              
year           2022                             
month          06                               
day            23                               
svn rev        82513                            
language       R                                
version.string R version 4.2.1 (2022-06-23 ucrt)
nickname       Funny-Looking Kid          

package.version("DOSE")
[1] "3.25.0.002"
> package.version("org.Hs.eg.db")
[1] "3.15.0"
> package.version("clusterProfiler")
[1] "4.7.1.003"

head(gene$ENTREZID,20)
 [1] "51106"  "6576"   "30001"  "126789" "2588"   "5720"   "148413" "55219" 
 [9] "10042"  "93587"  "201254" "26610"  "6301"   "63979"  "5150"   "5111"  
[17] "387263" "65003"  "51016"  "55703" 

 length(gene$ENTREZID)
[1] 2574

### Describe your issue

KEGG <- enrichKEGG(
  gene$ENTREZID,
  organism = "hsa", 
  keyType = "kegg",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  minGSSize = 10,
  maxGSSize = 500,
  qvalueCutoff = 0.05,
  use_internal_data = FALSE) 

--> No gene can be mapped....
--> Expected input gene ID: 
--> return NULL...

### Ask in the right place

The same ENTREZID, I can run normally in enrichGO, why not KEGG?

**Comment by Ww-Yxm** [comment]
I also encountered the same problem and am waiting for a solution

**Comment by ZhangZhenYang-zzy** [comment]
I also encountered the same problem

**Comment by Ww-Yxm** [comment]
Try “KEGG.db”

**Comment by lucygarner** [comment]
See #549.

`devtools::install_github("YuLab-SMU/clusterProfiler")`
