### ISSUE TITLE
compare cluster KEGG

### ISSUE THREAD

**Issue by swang872** [YuLab-SMU/clusterProfiler#580]
kk <- compareCluster(ENTREZID~cluster, data=mmm,
                             fun="enrichKEGG")

data from mouse
it shown "In compareCluster(ENTREZID ~ cluster, data = mmm, fun = "enrichKEGG") :
  No enrichment found in any of gene cluster, please check your input..."
but same data work in compare cluster enrichGO, and enrichKEGG. only no enrichment for comparecluster enrich KEGG

**Comment by yzh37545** [comment]
Same issue here. It worked several months ago. But can't find enrichment today using the same dataset.
"Warning messages:
1: In utils::download.file(url, quiet = TRUE, method = method, ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
2: In utils::download.file(url, quiet = TRUE, method = method, ...) :
  the 'wininet' method is deprecated for http:// and https:// URLs
3: In compareCluster(geneCluster = genelist, fun = "enrichKEGG", organism = "mmu") :
  No enrichment found in any of gene cluster, please check your input..."

**Comment by veramazzara** [comment]
I have got same problem, also with the package example:

data(gcSample)
xx <- compareCluster(gcSample, fun="enrichKEGG",
                     organism="hsa", pvalueCutoff=0.05)

Error in compareCluster(gcSample, fun = "enrichKEGG", organism = "hsa",  : 
  No enrichment found in any of gene cluster, please check your input...

**Comment by yzh37545** [comment]
I fixed the problem by updating to the newest version of R (4.3.0).

**Comment by Guerande29** [comment]
I fixed the problem by updating to the newest version of R (4.3.0) and using #install.packages("R.utils")
library(R.utils)
R.utils::setOption("clusterProfiler.download.method","auto") 

https://github.com/YuLab-SMU/clusterProfiler/issues/305#issuecomment-1211768515

**Comment by swang872** [comment]
> I fixed the problem by updating to the newest version of R (4.3.0).

thanks, works for me
