### ISSUE TITLE
Feature Request: Output GeneRatio and BgRatio as numeric from enrichGO

### ISSUE THREAD

**Issue by Charl-Hutchings** [YuLab-SMU/clusterProfiler#602]
Hello, 

### Background
I am currently using the `enrichGO` function within `clusterProfiler` to complete GO enrichment analyses. I then use the output (an object of class .. ) and plotting functions from `enrich plot` to visualise the results. 

### The problem
I want to plot my GO terms on the y-axis of bar plot, and then have the x-axis be an enrichment factor. This could be easily calculated by dividing `GeneRatio` by `BgRatio`. Unfortunately, this is not possible because of the way in which these data are contained as character variables. The character variables contain a / (e.g., "36/378"), which further prevents easy conversion to numeric. 

### The solution
Please could you alter the `enrichGO` function such that `GeneRatio` and `BgRatio` are numeric.

**Comment by suburbianmantia** [comment]
I don't know if this is what you are looking for but this could be a workaround : 

```
library(tidyverse)
library(clusterProfiler)
library(enrichplot)
library(org.Hs.eg.db)

enrich_object = enrichGO(names(geneList), OrgDb = org.Hs.eg.db)

make_ratio_numeric = function(ratio) {
  ratio = as.numeric(unlist(str_split(ratio, "/"))[1])/as.numeric(unlist(str_split(ratio, "/"))[2])
  ratio
}

return_num = function(ratio){
  num = as.numeric(unlist(str_split(ratio, "/"))[1])
  num
}

enrich_object@result$GeneRatio_num =  sapply(enrich_object@result$GeneRatio, make_ratio_numeric)
enrich_object@result$BgRatio_num = sapply(enrich_object@result$Bg, make_ratio_numeric)

#create new column : 
enrich_object@result$new_var = enrich_object@result$GeneRatio_num/enrich_object@result$BgRatio_num
enrich_object@result$RichFactor = sapply(enrich_object@result$GeneRatio, return_num)/sapply(enrich_object@result$BgRatio, return_num)

barplot(enrich_object, x = "RichFactor")
```
![image](https://github.com/YuLab-SMU/clusterProfiler/assets/74857304/0ecc892a-9c3f-46c8-8261-2661dab4eecd)

This is the image you're getting for the Rich Factor. I have also provided a calculation of the ratio of GeneRatio/BgRatio (see 'new_var')

**Comment by Charl-Hutchings** [comment]
Thank you very much!
