### ISSUE TITLE
OrgDB not supported anymore?

### ISSUE THREAD

**Issue by SauerTho** [YuLab-SMU/clusterProfiler#620]
Hey there,

I am experiencing erros regarding the OrgDB support. I have always used the gseGO function in the way proposed in the manual, defining the organism via OrgDb = org.Hs.eg.db. However, recently I am experiencing problems with the function, as I get he error message "there is no package called 'org.Hs.eg.eb'". 

Thanks for your insights!

**Comment by GuangchuangYu** [comment]
you need to install it first.

```
BiocManager::install("org.Hs.eg.db")
```
