### ISSUE TITLE
clusterProfiler custom annotated list

### ISSUE THREAD

**Issue by mansi-aggarwal-2504** [YuLab-SMU/clusterProfiler#655]
Hello, I want to conduct ORA using the ⁠` enricher ⁠` fucntion. In `TERM2GENE`, I pass the TF target genes in column 2, and column 1 is my annotation “TF”, which is the same for all rows.
Input is a list of genes. I wanted to check if the overlap between these two lists is significant.

However, I get a NULL result for all TF target genes and input genes combination:

<img width="342" alt="Screenshot 2024-01-06 at 8 19 50 am" src="https://github.com/YuLab-SMU/clusterProfiler/assets/60866597/321e5a02-0829-4e6a-8917-0f4a2da697fc">

Could anyone let me know where I am going wrong? 

Thanks.

**Comment by guidohooiveld** [comment]
Please refrain of posting the same question multiple times; you posted this one already 3 times (!) at the Bioconductor support forum... 

Are you sure that the number of  TF target genes is indeed less than 500? Based on the error message, this is the first thing to check!

**Comment by mansi-aggarwal-2504** [comment]
Apologies, I wasn't able to make an actual post due to a [forum glitch perhaps](https://support.bioconductor.org/p/9153645/) (?) and hence, I left comments on 3 very old but somewhat related posts.

However, thank you for your response. Let me troubleshoot my input lists again.
