### ISSUE TITLE
[feature request] Support metabolite enrichment analysis

### ISSUE THREAD

**Issue by Landau1994** [YuLab-SMU/clusterProfiler#668]
Will ClusterProfiler support metabolite enrichment analysis in the near future?

**Comment by guidohooiveld** [comment]
Note that I am not an expert on metabolomics.
Yet, my thoughts: by using the generic functions `enricher` and `GSEA` one could perform over-representations resp. enrichment analysis on _any_ type of data / input. So the analytical framework is already available. The question I have is what exactly is the type of input data you have in mind, and which source to use for predefined metabolite pathways and disease states?

**Comment by GuangchuangYu** [comment]
see the <https://github.com/YuLab-SMU/MicrobiomeProfiler> package.
