### ISSUE TITLE
feature request: add message suggesting to cite fgsea package when it's used for GSEA analysis

### ISSUE THREAD

**Issue by assaron** [YuLab-SMU/clusterProfiler#680]
Hi, I believe some of your package users don't realize that they rely on fgsea package when they do GSEA analysis with clusterProfiler and consequently don't cite it.  Could you please add a message suggesting users to cite fgsea when it's ran? For example, this is done in DESeq2 when a dedicated external method is used for logFC shrinkage: https://github.com/thelovelab/DESeq2/blob/devel/R/lfcShrink.R#L349

**Comment by guidohooiveld** [comment]
Sounds like a very reasonable request to me!

Actively pinging Guangchuang (@GuangchuangYu) since I expect he isn't checking the `clusterProfiler` GitHub every day.

**Comment by GuangchuangYu** [comment]
see <https://github.com/YuLab-SMU/DOSE/commit/320aba3dcb40b765412a3fcb6ad2b0cc0faffecf>.

**Comment by assaron** [comment]
Great, thanks!
