### ISSUE TITLE
size = qvalue does not work with ridgeplot function()

### ISSUE THREAD

**Issue by CharlineJnnt** [YuLab-SMU/clusterProfiler#704]
Hello, 

I have performed a GSEA enrichment analysis using data from the DOSE library, then, I ran the ridgeplot() function by changing values in the fill argument. I have tested the 3 available values, fill = "pvalue", fill = "p.adjust" and fill = "qvalue". It worked for the 2 first values but not for the last one. 

My code is
```
>library(DOSE)
>data(geneList)
>edo2 <- gseDO(geneList)
>ridgeplot(edo2, fill = "pvalue")
>ridgeplot(edo2, fill = "p.adjust")
>ridgeplot(edo2, fill = "qvalue")
Erreur dans ridgeplot.gseaResult(x, showCategory = showCategory, fill = fill,  :
'fill' variable not available ...
```
![image](https://github.com/YuLab-SMU/clusterProfiler/assets/94681105/aaf00a72-253f-44db-8979-fa4e28165eaa)

![image](https://github.com/YuLab-SMU/clusterProfiler/assets/94681105/d1a6f13f-7b91-433e-b2fd-429d9ea423fb)

Can you help me ?

**Comment by guidohooiveld** [comment]
I can reproduce your problem!

It is a bug in the code of the `ridgeplot` function (that actually is part of the `enrichplot` library).

Specifically these 2 lines:
```
    if (fill == "qvalue") {
        fill <- "qvalues"
    }
    if (!fill %in% colnames(x@result)) {
        stop("'fill' variable not available ...")
```

https://github.com/YuLab-SMU/enrichplot/blob/cc0980f2f49291bbd3ac4e0820e6646c58e86612/R/ridgeplot.R#L30-L34

Basically, when calling the `ridgeplot` function, if you define the argument `fill = "qvalue"`, then within the function the argument  `"qvalue"` is renamed to `"qvalues"` (thus with an `s`).

Yet, in the output there is **NO** column present named `qvalues`, but only `qvalue` (without an `s`), This throws the error...


A quick fix is to manually rename in the output the corresponding column to `qvalues` (thus with an `s`).

@GuangchuangYu : could you please fix this bug?


```
> library(DOSE)
> data(geneList)
> edo2 <- gseDO(geneList)
using 'fgsea' for GSEA analysis, please cite Korotkevich et al (2019).

preparing geneSet collections...
GSEA analysis...
leading edge analysis...
done...
>
> ## reported error is reproducible!
> 
> ridgeplot(edo2, fill = "qvalue")
Error in ridgeplot.gseaResult(x, showCategory = showCategory, fill = fill,  : 
  'fill' variable not available ...
> 
> ## check column names of the results
> ## note that the 8th column contains the qvalue.
> colnames(edo2@result)
 [1] "ID"              "Description"     "setSize"         "enrichmentScore"
 [5] "NES"             "pvalue"          "p.adjust"        "qvalue"         
 [9] "rank"            "leading_edge"    "core_enrichment"
> colnames(edo2@result)[8]
[1] "qvalue"
>
> ## renames 'qvalue' to 'qvalues' (thus with an s)
> colnames(edo2@result)[8] <- "qvalues"
>
> ## check
> colnames(edo2@result)[8]
[1] "qvalues"
>
> ## create ridgplot based on qvalue
> ## works!
>
> ridgeplot(edo2, fill = "qvalue")
Picking joint bandwidth of 0.225
>
``` 


![image](https://github.com/user-attachments/assets/ca582e97-f854-4def-8e67-60eda05fb30a)

**Comment by CharlineJnnt** [comment]
Thank you ! This fixes my bug !

**Comment by GuangchuangYu** [comment]
fixed and thanks, see <https://github.com/YuLab-SMU/enrichplot/commit/c7d162c84ef7fc6ac9942fee10ef4f7f50be43ca>.
