### ISSUE TITLE
gsePathway not found

### ISSUE THREAD

**Issue by NicoHadas** [YuLab-SMU/clusterProfiler#736]
Thank you for the great package!

Sorry if I missed an update, but it seems like gsePathway() function no longer works. 

`Upregulated.R <- gsePathway(Upregulated.GeneList)`
Error in gsePathway(Upregulated.GeneList) : 
  could not find function "gsePathway"

Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14)
 os       Ubuntu 24.04.1 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Chicago
 date     2024-10-24
 rstudio  2024.04.2+764 Chocolate Cosmos (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package              * version    date (UTC) lib source
   abind                  1.4-8      2024-09-12 [1] CRAN (R 4.4.1)
   AnnotationDbi        * 1.66.0     2024-05-01 [1] Bioconductor 3.19 (R 4.4.0)
   ape                    5.8        2024-04-11 [1] CRAN (R 4.4.0)
   aplot                  0.2.3      2024-06-17 [1] CRAN (R 4.4.0)
   basilisk               1.16.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.1)
   basilisk.utils         1.16.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.1)
   Biobase              * 2.64.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   BiocGenerics         * 0.50.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   BiocManager          * 1.30.25    2024-08-28 [1] CRAN (R 4.4.1)
   BiocParallel           1.38.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   Biostrings             2.72.1     2024-06-02 [1] Bioconductor 3.19 (R 4.4.0)
   bit                    4.5.0      2024-09-20 [1] CRAN (R 4.4.1)
   bit64                  4.5.2      2024-09-22 [1] CRAN (R 4.4.1)
   bitops                 1.0-9      2024-10-03 [1] CRAN (R 4.4.1)
   blob                   1.2.4      2023-03-17 [1] CRAN (R 4.4.0)
   cachem                 1.1.0      2024-05-16 [1] CRAN (R 4.4.0)
   cli                    3.6.3      2024-06-21 [1] CRAN (R 4.4.1)
   cluster                2.1.6      2023-12-01 [1] CRAN (R 4.4.1)
   clusterProfiler      * 4.12.6     2024-08-25 [1] Bioconductor 3.19 (R 4.4.1)
   clustree             * 0.5.1      2023-11-05 [1] CRAN (R 4.4.0)
   codetools              0.2-20     2024-03-31 [4] CRAN (R 4.4.0)
   colorspace             2.1-1      2024-07-26 [1] CRAN (R 4.4.1)
   cowplot                1.1.3      2024-01-22 [1] CRAN (R 4.4.0)
   crayon                 1.5.3      2024-06-20 [1] CRAN (R 4.4.0)
   data.table             1.16.2     2024-10-10 [1] CRAN (R 4.4.1)
   DBI                    1.2.3      2024-06-02 [1] CRAN (R 4.4.0)
   DelayedArray           0.30.1     2024-05-07 [1] Bioconductor 3.19 (R 4.4.0)
   deldir                 2.0-4      2024-02-28 [1] CRAN (R 4.4.0)
   devtools             * 2.4.5      2022-10-11 [1] CRAN (R 4.4.1)
   dichromat              2.0-0.1    2022-05-02 [1] CRAN (R 4.4.0)
   digest                 0.6.37     2024-08-19 [1] CRAN (R 4.4.1)
   dir.expiry             1.12.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.1)
   DOSE                   3.30.5     2024-09-01 [1] Bioconductor 3.19 (R 4.4.1)
   dotCall64              1.2        2024-10-04 [1] CRAN (R 4.4.1)
   DoubletFinder        * 2.0.4      2024-06-13 [1] Github (chris-mcginnis-ucsf/DoubletFinder@03e9f37)
   dplyr                * 1.1.4      2023-11-17 [1] CRAN (R 4.4.1)
   ellipsis               0.3.2      2021-04-29 [1] CRAN (R 4.4.0)
   enrichplot             1.24.4     2024-09-01 [1] Bioconductor 3.19 (R 4.4.1)
   fansi                  1.0.6      2023-12-08 [1] CRAN (R 4.4.0)
   farver                 2.1.2      2024-05-13 [1] CRAN (R 4.4.0)
   fastDummies            1.7.4      2024-08-16 [1] CRAN (R 4.4.1)
   fastmap                1.2.0      2024-05-15 [1] CRAN (R 4.4.0)
   fastmatch              1.1-4      2023-08-18 [1] CRAN (R 4.4.0)
   fgsea                  1.30.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   filelock               1.0.3      2023-12-11 [1] CRAN (R 4.4.1)
   fitdistrplus           1.2-1      2024-07-12 [1] CRAN (R 4.4.1)
   forcats              * 1.0.0      2023-01-29 [1] CRAN (R 4.4.0)
   fs                     1.6.4      2024-04-25 [1] CRAN (R 4.4.0)
   future                 1.34.0     2024-07-29 [1] CRAN (R 4.4.1)
   future.apply           1.11.2     2024-03-28 [1] CRAN (R 4.4.0)
   generics               0.1.3      2022-07-05 [1] CRAN (R 4.4.0)
   GenomeInfoDb           1.40.1     2024-05-24 [1] Bioconductor 3.19 (R 4.4.0)
   GenomeInfoDbData       1.2.12     2024-06-13 [1] Bioconductor
 V GenomicRanges          1.56.1     2024-10-09 [1] Bioconductor 3.19 (R 4.4.1) (on disk 1.56.2)
   ggforce                0.4.2      2024-02-19 [1] CRAN (R 4.4.0)
   ggfun                  0.1.6      2024-08-28 [1] CRAN (R 4.4.1)
   ggplot2              * 3.5.1      2024-04-23 [1] CRAN (R 4.4.0)
   ggplotify              0.1.2      2023-08-09 [1] CRAN (R 4.4.0)
   ggraph               * 2.2.1      2024-03-07 [1] CRAN (R 4.4.0)
   ggrepel                0.9.6      2024-09-07 [1] CRAN (R 4.4.1)
   ggridges               0.5.6      2024-01-23 [1] CRAN (R 4.4.0)
   ggtree                 3.12.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   globals                0.16.3     2024-03-08 [1] CRAN (R 4.4.0)
   glue                   1.8.0      2024-09-30 [1] CRAN (R 4.4.1)
   GO.db                  3.19.1     2024-06-13 [1] Bioconductor
   goftest                1.2-3      2021-10-07 [1] CRAN (R 4.4.0)
   GOSemSim               2.30.2     2024-08-21 [1] Bioconductor 3.19 (R 4.4.1)
   graphlayouts           1.2.0      2024-09-24 [1] CRAN (R 4.4.1)
   gridExtra            * 2.3        2017-09-09 [1] CRAN (R 4.4.1)
   gridGraphics           0.5-1      2020-12-13 [1] CRAN (R 4.4.0)
   gson                   0.1.0      2023-03-07 [1] CRAN (R 4.4.0)
   gtable                 0.3.5      2024-04-22 [1] CRAN (R 4.4.0)
   harmony              * 1.2.1      2024-08-27 [1] CRAN (R 4.4.1)
   hdf5r                * 1.3.11     2024-07-07 [1] CRAN (R 4.4.1)
   here                   1.0.1      2020-12-13 [1] CRAN (R 4.4.0)
   HGNChelper           * 0.8.14     2024-05-18 [1] CRAN (R 4.4.1)
   hms                    1.1.3      2023-03-21 [1] CRAN (R 4.4.0)
   htmltools              0.5.8.1    2024-04-04 [1] CRAN (R 4.4.0)
   htmlwidgets            1.6.4      2023-12-06 [1] CRAN (R 4.4.0)
   httpuv                 1.6.15     2024-03-26 [1] CRAN (R 4.4.0)
   httr                   1.4.7      2023-08-15 [1] CRAN (R 4.4.0)
   httr2                  1.0.5      2024-09-26 [1] CRAN (R 4.4.1)
   ica                    1.0-3      2022-07-08 [1] CRAN (R 4.4.0)
 V igraph                 2.0.3      2024-10-19 [1] CRAN (R 4.4.1) (on disk 2.1.1)
   IRanges              * 2.38.1     2024-07-03 [1] Bioconductor 3.19 (R 4.4.1)
   irlba                  2.3.5.1    2022-10-03 [1] CRAN (R 4.4.0)
   jsonlite               1.8.9      2024-09-20 [1] CRAN (R 4.4.1)
   KEGGREST               1.44.1     2024-06-19 [1] Bioconductor 3.19 (R 4.4.1)
   KernSmooth             2.23-24    2024-05-17 [4] CRAN (R 4.4.0)
   labeling               0.4.3      2023-08-29 [1] CRAN (R 4.4.0)
   later                  1.3.2      2023-12-06 [1] CRAN (R 4.4.0)
   lattice                0.22-6     2024-03-20 [1] CRAN (R 4.4.0)
   lazyeval               0.2.2      2019-03-15 [1] CRAN (R 4.4.0)
   leiden               * 0.4.3.1    2024-07-02 [1] Github (TomKellyGenetics/leiden@22ae49d)
   lifecycle              1.0.4      2023-11-07 [1] CRAN (R 4.4.0)
   limma                  3.60.6     2024-10-02 [1] Bioconductor 3.19 (R 4.4.1)
   listenv                0.9.1      2024-01-29 [1] CRAN (R 4.4.0)
   lmtest                 0.9-40     2022-03-21 [1] CRAN (R 4.4.0)
   lubridate            * 1.9.3      2023-09-27 [1] CRAN (R 4.4.0)
   magrittr               2.0.3      2022-03-30 [1] CRAN (R 4.4.0)
   mapproj                1.2.11     2023-01-12 [1] CRAN (R 4.4.0)
   maps                   3.4.2      2023-12-15 [1] CRAN (R 4.4.0)
   MASS                   7.3-61     2024-06-13 [1] CRAN (R 4.4.0)
   mathjaxr               1.6-0      2022-02-28 [1] CRAN (R 4.4.0)
   Matrix                 1.7-0      2024-04-26 [4] CRAN (R 4.4.0)
   MatrixGenerics         1.16.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   matrixStats            1.4.1      2024-09-08 [1] CRAN (R 4.4.1)
   memoise                2.0.1      2021-11-26 [1] CRAN (R 4.4.0)
   metap                * 1.11       2024-07-11 [1] CRAN (R 4.4.1)
   mime                   0.12       2021-09-28 [1] CRAN (R 4.4.0)
   miniUI                 0.1.1.1    2018-05-18 [1] CRAN (R 4.4.0)
   mnormt                 2.1.1      2022-09-26 [1] CRAN (R 4.4.0)
   multcomp               1.4-26     2024-07-18 [1] CRAN (R 4.4.1)
   multtest             * 2.60.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   munsell                0.5.1      2024-04-01 [1] CRAN (R 4.4.0)
   mutoss                 0.1-13     2023-03-14 [1] CRAN (R 4.4.0)
   mvtnorm                1.3-1      2024-09-03 [1] CRAN (R 4.4.1)
   nlme                   3.1-165    2024-06-06 [4] CRAN (R 4.4.0)
   numDeriv               2016.8-1.1 2019-06-06 [1] CRAN (R 4.4.0)
   org.Hs.eg.db         * 3.19.1     2024-06-13 [1] Bioconductor
   pals                 * 1.9        2024-07-16 [1] CRAN (R 4.4.1)
   parallelly             1.38.0     2024-07-27 [1] CRAN (R 4.4.1)
   patchwork            * 1.3.0      2024-09-16 [1] CRAN (R 4.4.1)
   pbapply                1.7-2      2023-06-27 [1] CRAN (R 4.4.0)
   pillar                 1.9.0      2023-03-22 [1] CRAN (R 4.4.0)
   pkgbuild               1.4.4      2024-03-17 [1] CRAN (R 4.4.0)
   pkgconfig              2.0.3      2019-09-22 [1] CRAN (R 4.4.0)
   pkgload                1.4.0      2024-06-28 [1] CRAN (R 4.4.1)
   plotly                 4.10.4     2024-01-13 [1] CRAN (R 4.4.1)
   plotrix                3.8-4      2023-11-10 [1] CRAN (R 4.4.0)
   plyr                   1.8.9      2023-10-02 [1] CRAN (R 4.4.0)
   png                    0.1-8      2022-11-29 [1] CRAN (R 4.4.0)
   polyclip               1.10-7     2024-07-23 [1] CRAN (R 4.4.1)
   presto                 1.0.0      2024-06-20 [1] Github (immunogenomics/presto@7636b3d)
   profvis                0.4.0      2024-09-20 [1] CRAN (R 4.4.1)
   progressr              0.14.0     2023-08-10 [1] CRAN (R 4.4.0)
   promises               1.3.0      2024-04-05 [1] CRAN (R 4.4.0)
   purrr                * 1.0.2      2023-08-10 [1] CRAN (R 4.4.0)
   qqconf                 1.3.2      2023-04-14 [1] CRAN (R 4.4.0)
   qvalue                 2.36.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   R.methodsS3            1.8.2      2022-06-13 [1] CRAN (R 4.4.1)
   R.oo                   1.26.0     2024-01-24 [1] CRAN (R 4.4.1)
   R.utils                2.12.3     2023-11-18 [1] CRAN (R 4.4.1)
   R6                     2.5.1      2021-08-19 [1] CRAN (R 4.4.0)
   RANN                   2.6.2      2024-08-25 [1] CRAN (R 4.4.1)
   rappdirs               0.3.3      2021-01-31 [1] CRAN (R 4.4.0)
   rbibutils              2.3        2024-10-04 [1] CRAN (R 4.4.1)
   RColorBrewer           1.1-3      2022-04-03 [1] CRAN (R 4.4.0)
   Rcpp                 * 1.0.13     2024-07-17 [1] CRAN (R 4.4.1)
   RcppAnnoy              0.0.22     2024-01-23 [1] CRAN (R 4.4.0)
   RcppHNSW               0.6.0      2024-02-04 [1] CRAN (R 4.4.0)
   RCurl                  1.98-1.16  2024-07-11 [1] CRAN (R 4.4.1)
   Rdpack                 2.6.1      2024-08-06 [1] CRAN (R 4.4.1)
   readr                * 2.1.5      2024-01-10 [1] CRAN (R 4.4.0)
   remotes                2.5.0      2024-03-17 [1] CRAN (R 4.4.0)
   reshape2               1.4.4      2020-04-09 [1] CRAN (R 4.4.0)
   reticulate             1.39.0     2024-09-05 [1] CRAN (R 4.4.1)
   rjson                  0.2.23     2024-09-16 [1] CRAN (R 4.4.1)
   rlang                  1.1.4      2024-06-04 [1] CRAN (R 4.4.0)
   ROCR                   1.0-11     2020-05-02 [1] CRAN (R 4.4.0)
   rprojroot              2.0.4      2023-11-05 [1] CRAN (R 4.4.0)
   RSpectra               0.16-2     2024-07-18 [1] CRAN (R 4.4.1)
   RSQLite                2.3.7      2024-05-27 [1] CRAN (R 4.4.0)
 V rstudioapi             0.16.0     2024-10-16 [1] CRAN (R 4.4.1) (on disk 0.17.0)
   Rtsne                  0.17       2023-12-07 [1] CRAN (R 4.4.0)
   rWikiPathways        * 1.24.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   S4Arrays               1.4.1      2024-05-20 [1] Bioconductor 3.19 (R 4.4.0)
   S4Vectors            * 0.42.1     2024-07-03 [1] Bioconductor 3.19 (R 4.4.1)
   sandwich               3.1-1      2024-09-15 [1] CRAN (R 4.4.1)
   scales                 1.3.0      2023-11-28 [1] CRAN (R 4.4.0)
   scattermore            1.2        2023-06-12 [1] CRAN (R 4.4.0)
   scatterpie             0.2.4      2024-08-28 [1] CRAN (R 4.4.1)
   sctransform          * 0.4.1      2023-10-19 [1] CRAN (R 4.4.0)
   sessioninfo            1.2.2      2021-12-06 [1] CRAN (R 4.4.0)
   Seurat               * 5.1.0      2024-05-10 [1] CRAN (R 4.4.1)
   SeuratData           * 0.2.2.9001 2024-06-13 [1] Github (satijalab/seurat-data@4dc08e0)
   SeuratDisk           * 0.0.0.9021 2024-06-13 [1] Github (mojaveazure/seurat-disk@877d4e1)
   SeuratObject         * 5.0.2      2024-05-08 [1] CRAN (R 4.4.0)
   shadowtext             0.1.4      2024-07-18 [1] CRAN (R 4.4.1)
   shiny                  1.9.1      2024-08-01 [1] CRAN (R 4.4.1)
   SingleCellExperiment   1.26.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   sn                     2.1.1      2023-04-04 [1] CRAN (R 4.4.0)
   sp                   * 2.1-4      2024-04-30 [1] CRAN (R 4.4.0)
   spam                   2.11-0     2024-10-03 [1] CRAN (R 4.4.1)
   SparseArray            1.4.8      2024-05-24 [1] Bioconductor 3.19 (R 4.4.0)
   spatstat.data          3.1-2      2024-06-21 [1] CRAN (R 4.4.1)
 V spatstat.explore       3.3-2      2024-10-22 [1] CRAN (R 4.4.1) (on disk 3.3.3)
   spatstat.geom          3.3-3      2024-09-18 [1] CRAN (R 4.4.1)
   spatstat.random        3.3-2      2024-09-18 [1] CRAN (R 4.4.1)
   spatstat.sparse        3.1-0      2024-06-21 [1] CRAN (R 4.4.1)
   spatstat.univar        3.0-1      2024-09-05 [1] CRAN (R 4.4.1)
   spatstat.utils         3.1-0      2024-08-17 [1] CRAN (R 4.4.1)
   splitstackshape        1.4.8      2019-04-21 [1] CRAN (R 4.4.1)
   statmod                1.5.0      2023-01-06 [1] CRAN (R 4.4.1)
   stringi                1.8.4      2024-05-06 [1] CRAN (R 4.4.0)
   stringr              * 1.5.1      2023-11-14 [1] CRAN (R 4.4.0)
   SummarizedExperiment   1.34.0     2024-05-01 [1] Bioconductor 3.19 (R 4.4.0)
   survival               3.7-0      2024-06-05 [4] CRAN (R 4.4.0)
   tensor                 1.5        2012-05-05 [1] CRAN (R 4.4.0)
   TFisher                0.2.0      2018-03-21 [1] CRAN (R 4.4.0)
   TH.data                1.1-2      2023-04-17 [1] CRAN (R 4.4.0)
   tibble               * 3.2.1      2023-03-20 [1] CRAN (R 4.4.0)
   tidygraph              1.3.1      2024-01-30 [1] CRAN (R 4.4.0)
   tidyr                * 1.3.1      2024-01-24 [1] CRAN (R 4.4.0)
   tidyselect             1.2.1      2024-03-11 [1] CRAN (R 4.4.0)
   tidytree               0.4.6      2023-12-12 [1] CRAN (R 4.4.0)
   tidyverse            * 2.0.0      2023-02-22 [1] CRAN (R 4.4.1)
   timechange             0.3.0      2024-01-18 [1] CRAN (R 4.4.0)
   treeio                 1.28.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   tweenr                 2.0.3      2024-02-26 [1] CRAN (R 4.4.0)
   tzdb                   0.4.0      2023-05-12 [1] CRAN (R 4.4.0)
   UCSC.utils             1.0.0      2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   urlchecker             1.0.1      2021-11-30 [1] CRAN (R 4.4.0)
   usethis              * 3.0.0      2024-07-29 [1] CRAN (R 4.4.1)
   utf8                   1.2.4      2023-10-22 [1] CRAN (R 4.4.0)
   uwot                   0.2.2      2024-04-21 [1] CRAN (R 4.4.0)
   vctrs                  0.6.5      2023-12-01 [1] CRAN (R 4.4.0)
   viridis                0.6.5      2024-01-29 [1] CRAN (R 4.4.0)
   viridisLite            0.4.2      2023-05-02 [1] CRAN (R 4.4.0)
   withr                  3.0.1      2024-07-31 [1] CRAN (R 4.4.1)
   XML                    3.99-0.17  2024-06-25 [1] CRAN (R 4.4.1)
   xtable                 1.8-4      2019-04-21 [1] CRAN (R 4.4.0)
   XVector                0.44.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   yulab.utils            0.1.7      2024-08-26 [1] CRAN (R 4.4.1)
   zellkonverter        * 1.14.1     2024-06-23 [1] Bioconductor 3.19 (R 4.4.1)
   zlibbioc               1.50.0     2024-04-30 [1] Bioconductor 3.19 (R 4.4.0)
   zoo                    1.8-12     2023-04-13 [1] CRAN (R 4.4.0)

 [1] /home/nico/R/x86_64-pc-linux-gnu-library/4.4
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

 V ── Loaded and on-disk version mismatch.

─ Python configuration ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 python:         /home/nico/.virtualenvs/r-reticulate/bin/python
 libpython:      /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12.so
 pythonhome:     /home/nico/.virtualenvs/r-reticulate:/home/nico/.virtualenvs/r-reticulate
 version:        3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
 numpy:          /home/nico/.virtualenvs/r-reticulate/lib/python3.12/site-packages/numpy
 numpy_version:  2.0.0
 pandas:         /home/nico/.virtualenvs/r-reticulate/lib/python3.12/site-packages/pandas

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
>

Regards

**Comment by guidohooiveld** [comment]
What you missed is that the function `gsePathway` is part of the package `ReactomePA` , and not `clusterProfiler`. :-)

```
> library(clusterProfiler)
> 
> data(geneList, package = "DOSE")
> yy <-  gsePathway(geneList, organism = "human", eps=0)
Error in gsePathway(geneList, organism = "human", eps = 0) : 
  could not find function "gsePathway"
> 
> library(ReactomePA)
ReactomePA v1.48.0  For help: https://yulab-smu.top/biomedical-knowledge-mining-book/

If you use ReactomePA in published research, please cite:
Guangchuang Yu, Qing-Yu He. ReactomePA: an R/Bioconductor package for reactome pathway analysis and visualization. Molecular BioSystems 2016, 12(2):477-479
> yy <-  gsePathway(geneList, organism = "human", eps=0)
>
> <<snip>>
>
> yy
#
# Gene Set Enrichment Analysis
#
#...@organism    human 
#...@setType     Reactome 
#...@keytype     ENTREZID 
#...@geneList    Named num [1:12495] 4.57 4.51 4.42 4.14 3.88 ...
 - attr(*, "names")= chr [1:12495] "4312" "8318" "10874" "55143" ...
#...nPerm        
#...pvalues adjusted by 'BH' with cutoff <0.05 
#...316 enriched terms found
'data.frame':   316 obs. of  11 variables:
 $ ID             : chr  "R-HSA-69278" "R-HSA-69620" "R-HSA-68882" "R-HSA-2555396" ...
 $ Description    : chr  "Cell Cycle, Mitotic" "Cell Cycle Checkpoints" "Mitotic Anaphase" "Mitotic Metaphase and Anaphase" ...
 $ setSize        : int  458 237 199 200 325 142 136 124 134 110 ...
 $ enrichmentScore: num  0.607 0.668 0.648 0.65 0.548 ...
 $ NES            : num  2.91 3.04 2.92 2.92 2.58 ...
 $ pvalue         : num  3.45e-49 1.00e-35 1.14e-27 3.33e-27 1.09e-25 ...
 $ p.adjust       : num  5.28e-46 7.65e-33 5.80e-25 1.27e-24 3.33e-23 ...
 $ qvalue         : num  3.99e-46 5.79e-33 4.39e-25 9.61e-25 2.52e-23 ...
 $ rank           : num  1769 1905 1857 1857 1857 ...
 $ leading_edge   : chr  "tags=36%, list=14%, signal=32%" "tags=43%, list=15%, signal=37%" "tags=39%, list=15%, signal=34%" "tags=40%, list=15%, signal=34%" ...
 $ core_enrichment: chr  "8318/55143/55388/991/2305/9493/1062/4605/9133/10403/7153/23397/6241/11065/220134/22974/4751/79019/55839/27338/8"| __truncated__ "8318/55143/55388/991/1062/9133/10403/11065/220134/79019/55839/27338/890/983/54821/4085/81930/332/9212/1111/891/"| __truncated__ "55143/991/1062/9133/10403/11065/220134/79019/55839/27338/983/54821/4085/81930/332/9212/891/9232/4001/11004/5347"| __truncated__ "55143/991/1062/9133/10403/11065/220134/79019/55839/27338/983/54821/4085/81930/332/9212/891/9232/4001/11004/5347"| __truncated__ ...
#...Citation
Guangchuang Yu, Qing-Yu He. ReactomePA: an R/Bioconductor package for reactome pathway analysis and visualization. Molecular BioSystems. 2016, 12(2):477-479 

> 
> dotplot(yy)
> 
```


![image](https://github.com/user-attachments/assets/9a8b535c-7ac9-4150-84b5-ffc6da2ef164)
