### ISSUE TITLE
CompareCluster with custom GO annotation

### ISSUE THREAD

**Issue by marcodimarsico** [YuLab-SMU/clusterProfiler#748]
Hi, 
thank you very much for this amazing package. 

I was wondering if it could be possible to use the clusterProfiler function compareCluster() with a custom GO annotation. 

Specifically I was thinking to use the fuction with the following parameters, but for the species that I am working with no OrgDb are available. 

`ckvf = compareCluster(geneClusters = modsvf, fun = "enrichGO", keyType = "GID",ont = "ALL", OrgDb = org.YYY.eg.db)
`

Is there an alternative way to set the parameters by using as annotation a tsv file composed by the GeneID with the GO terms associated with it?

Thank you very much in advance.

**Comment by guidohooiveld** [comment]
Yes, this is possible. Yet, you will need to use the generic function `enricher` to do this, in which a `TERM2GENE` dataframe is specified and provided. `TERM2GENE` contains the (custom) mapping from GO term vs gene id. 

To get some inspiration, see for example section "_B) combined analysis_" in my post here. https://github.com/YuLab-SMU/clusterProfiler/issues/678#issuecomment-2027468095

Note that in this post the (combined) `TERM2GENE` input is generated by querying the `GO.db` and KEGG online, but you will obviously need to import the `tsv` file to create this dataframe.
For easy interpretation of the results, it would also be good to have a `TERM2NAME` dataframe. You can generate this using the `GO.db` (see my post).

**Comment by marcodimarsico** [comment]
Thank you very much!
